jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java

Enforcing check on Element error-page/location to have a leading '/' as per the Servlet specification, section 14.4.15
Signed-off-by: Mehtab Singh Mann <mehtabsinghmann@gmail.com>

Issue #356 (Element error-page/location must start with a '/')

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java

+ If request has no 'Accept' header, produce text/html as before.
+ If request has 'Accept' header, then test for 'text/html' or '*/*'
entries before producing html output.

Issue #124 - Don't produce text/html if the request doesn't accept it

---

jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2.java

- Can override 'onClose' method and get GoAwayFrame.
- Related PR: https://github.com/eclipse/jetty.project/pull/389
Signed-off-by: Jinho Shin <drdoteam@gmail.com>

Add a overridable 'onClose' method in HttpClientTransportOverHTTP2

---

jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/messages/BinaryPartialMessage.java
jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/MessageReceivingTest.java

Fixed #437 
Added unit tests for the case for both text and binary messages

Fix #437 Avoid NPE on receiving empty message though MessageHandler.Partial

---

jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
jetty-util/src/main/java/org/eclipse/jetty/util/resource/FileResource.java
jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
jetty-util/src/test/java/org/eclipse/jetty/util/StringUtilTest.java
jetty-util/src/test/java/org/eclipse/jetty/util/resource/AbstractFSResourceTest.java
jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileResourceTest.java

+ Adding testcases
+ Cleaning up unit tests, adding more
+ Fixing one testcase related to FileResource.addPath()
+ Adding validation of filesystem paths

Issue #438 - File and Path Resources with control characters should be rejected

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java

All google server answer bad request when Host field is filled in h2 protocol.
Change-Id: I9e16f8c9f56bc26df0b0a933cee0b3a3d6c31921

[Jetty-Client] fix: don't add host automaticaly on http2 request.

---

jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java

I noticed the canonicaPath method was so complicated to understand and had duplicated code, so I improved it and now is shorter and runs faster

Improve canonicalPath method in URIUtilTest.java

---

jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java

With this I am simplifying the code to verify paths already tried on PR #460 that had to be reverted due to a test not contemplated and now added on #466. This time it works fine for all the tests.

Improve canonicalPath method in URIUtil.java contemplating new test added on issue #466

---

jetty-osgi/jetty-osgi-boot/pom.xml

Signed-off-by: laeubi <laeubi@laeubi-soft.de>
Makes the import optional.

Fix #480 [jetty-osgi] org.eclipse.jetty.annotations should be optional

---

jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/OSGiClassLoader.java

Next try now with signed commit. I noticed that the same might apply to Webappclasslaoder.

Fix #493 OSGiClassLoader contains dead code

---

CODE_COVERAGE.md
jetty-http-spi/pom.xml
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/DelegateThreadPoolBase.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/DelegatingThreadPoolBasicOperationsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/DelegatingThreadPoolExceptionTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/HttpSpiContextHandlerTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpContextTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpExchangeAdvancedOperationsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpExchangeBase.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpExchangeBasicOperationsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegateTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerBase.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerCreateContextBase.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerCreateContextTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerExceptionsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerProviderTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpServerTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpsExchangeAdvancedOperationsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpsExchangeBase.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JettyHttpsExchangeBasicOperationsTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/PojoTest.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestSPIServer.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/util/Pool.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/util/PrintTask.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/util/SpiConstants.java
jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/util/SpiUtility.java

Dear Team,
This pull request is focused on http-spi module.
Code coverage is measured using JaCoCo. This pull request increases code 
coverage of the whole project by 90%.
Metric             | Before| After
------------------|----------|-------
Coverage%    |0%     |90%
Lines Covered|0      |317
Total Lines      |349     |349
Please let me know if you have any questions.
Vijay
DevFactory - Code Quality Team.
commit ca9227e961ca074d4bfa42d801d7aeb810af98b4
Author: Charu <Charu>
Date:   Wed Dec 23 20:58:54 2015 +0530
Added Review Comments
commit ff30f698bfacd769b96f74c8c2a3a621900b5239
Author: Charu <Charu>
Date:   Wed Dec 23 09:56:07 2015 +0530
Unit tests for http-spi UTS-60

http-spi test improvement

---

jetty-documentation/src/main/asciidoc/development/websockets/jetty/jetty-websocket-api-session.adoc

Because that method has been removed in jetty-9.1 branch according to Bug 412439
Signed-off-by: Alexander Farber <Alexander.Farber@gmail.com>

Remove Session.setMaximumMessageSize(long) example

---

jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/DefaultJettyAtJettyHomeHelper.java
jetty-osgi/test-jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-with-custom-class.xml
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/SomeCustomBean.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithBundle.java

For any reason this contains a commit for #480, please ignore this and just merge the commit for #482

Fix #482 The CCL while parsing the xml files should be set to a combination of Jetty and Bundle-Classloader

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java

Support using direct byte buffers in the internal Jetty buffer pool (see: issue #351).

master: Support Direct Byte Buffers

---

jetty-server/src/main/java/org/eclipse/jetty/server/AbstractNCSARequestLog.java
jetty-server/src/test/java/org/eclipse/jetty/server/handler/RequestLogTest.java

It was brought to my attention ( https://github.com/nielsbasjes/logparser/issues/30 ) that when using the extended NCSARequestLog and there was no User-Agent request header that the resulting logfile has an additional space that should not be there.
This pull request fixes this and introduces a few tests to validate it.

Fix NCSA request log in case of missing useragent.

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java

Fix bug when asynchronous writes of Heap ByteBuffer were ignored.
ByteBuffer position was moved to the end in the constructor,
then in the `process` method `if (_buffer.hasRemaining())` condition
was always evaluated to `false` and the actual write was not performed.
Add assertion in `HttpOutputTest` to verify that after the asynchronous
write position of the buffer is always at the end.

HttpOtput: fix async write for heap ByteBuffer

---

jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/AbstractTest.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/AsyncServletTest.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/IdleTimeoutTest.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/frames/GoAwayFrame.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnectionFactory.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpChannelOverHTTP2.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java

Introduced new method HttpChannelState.asyncError() to be called in
case of asynchronous errors, i.e. those errors that do not happen in
the HttpChannel.handle() loop.
Implemented HTTP/2 callbacks to call HttpChannelState.asyncError()
and plug in the existing error handling mechanism.

Changes for Issue #824

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java

Make HttpClient#copyRequest to copy custom headers with the same values.
When original request contains some custom header, say `X-Custom`, than
HttpHeader object within a HttpField will be `null`. In such case
`newRequest.getHeaders().contains(field.getName(), value)` check returns
true when there are 2 and more custom headers with the same value. As a result
not all the custom headers are being copied to the new request.

Fix HttpClient#copyRequest

---

jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/util/ReflectUtils.java

Hey,
I just noticed a small possible improvement in ReflectUtils by precompiling the pattern in order to check for javax classes instead of compiling the pattern on every check.
Fixes #1004 
Cheers,
Christoph

Precompile pattern for checking of classes in javax package in ReflectUtils

---

jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
jetty-server/src/test/java/org/eclipse/jetty/server/InsufficientThreadsDetectionTest.java

**Problem:**
The server cares about selectors and acceptors even in the case of connector uses dedicated executor. This is wrong behaviour because of selectors and acceptors will never executed in server executor, so server should not try check limit in this case.
**Impact:**
In case of dedicated executor for connector, It is impossible to set the small max-size to server pool, because server requires threads which will never used.
**Workaround:**
Set required max thread count for server executor.
**Implemented fix:**
Configuration of connector has no impact to the insufficient thread detection at server level if connector uses own executor.

Enhancement for detection of insufficient threads

---

jetty-nosql/src/main/java/org/eclipse/jetty/nosql/mongodb/MongoSessionIdManager.java

MongoSessionIdManager scavenged immortal sessions (expiry <= 0) by accident. The third query condition (expiry $lt) overwrote the second (expiry $gt). BasicDBObject is a Map.
Query was:
`.find({ _id: { $in: ... }, expiry: { $lt: atTime } })`
After pull request:
`.find({ _id: { $in: ... }, expiry: { $gt: 0, $lt: atTime } })`

Fix for MongoSessionIdManager's scavenging of immortal sessions

---

jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc

This change fixes a location in the documentation where the artifact ID
of the plugin was still `maven-jetty-plugin`, where it should be
`jetty-maven-plugin`.
Signed-off-by: Jens Reimann <jreimann@redhat.com>

Fix wrong artifact ID of maven plugin

---

jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyDeployWar.java

This change allows to provide the `daemon` parameter using a property
using `-Djetty.daemon` in addition.
Signed-off-by: Jens Reimann <jreimann@redhat.com>
---
It looks like the file was checked in with CRLF line endings. I tried to keep it that way.

Allow to externally provide 'daemon' parameter

---

jetty-client/src/main/java/org/eclipse/jetty/client/GZIPContentDecoder.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java

Previously the GZIPContentDecoder would allocate a new buffer for
each gzip encoded response.

HttpClient GZIPContentDecoder uses client ByteBufferPool

---

jetty-nosql/src/main/java/org/eclipse/jetty/nosql/mongodb/MongoSessionDataStore.java

This is the version 9.4.x equivalent of https://github.com/eclipse/jetty.project/pull/1080. 
MongoSessionDataStore scavenges immortal sessions (expiry <= 0) by accident. The third query condition (expiry $lt) overwrote the second one (expiry $gt). BasicDBObject is a Map.
Query was:
`.find({ _id: { $in: ... }, expiry: { $lt: atTime } })`
After pull request:
`.find({ _id: { $in: ... }, expiry: { $gt: 0, $lt: atTime } })`

MongoSessionDataStore: fix for scavenging of local immortal sessions

---

jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/ConfiguratorTest.java

Signed-off-by: Stefan Schmidt <stefanschmidt@web.de>
Hi,
I've noticed that one test is failing on my machine because the implementation of the tests assumes the system locale to be set to 'English". This should not be the case for every machine this software is build.

Fixing system locale dependent test

---

jetty-http/pom.xml

This allows Eclipse to continue to make use of jetty-http
without requiring the presence of Apache Aries bundles.
This fixes a problem introduced by the resolution to #1290 
See also the discussion here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=512807
Signed-off-by: Mat Booth <mat.booth@redhat.com>

Make the requirement on "osgi.serviceloader.processor" optional

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java

Looks like this leak shows itself only with asynchronous responses.
Some relevant info: http://www.devguli.com/blog/eng/java-deflater-and-outofmemoryerror/

Fix native memory leak in GzipHandler

---

jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java

Hello,
Since Jetty 9.3.9, or since fixing issue #556, `PathResource` no longer correctly works with UNC paths.
The added `checkAliasPath` uses the `new File(uri).toPath()` construction, with the uri resulting from a `Path#toUri`, throwing:
```
java.lang.IllegalArgumentException: URI has an authority component
at java.io.File.<init>(File.java:423) ~[na:1.8.0_66]
at org.eclipse.jetty.util.resource.PathResource.checkAliasPath(PathResource.java:76) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
at org.eclipse.jetty.util.resource.PathResource.<init>(PathResource.java:207) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
at org.eclipse.jetty.util.resource.PathResource.addPath(PathResource.java:294) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
at …
```

Make PathResource UNC compatible again

---

jetty-http/pom.xml

Follow-up to acf3608 that was submitted in PR #1365.
I did not initially recognise that this second capability should also be optional in order for Eclipse to continue to make use of jetty-http without requiring the presence of Apache Aries bundles.
Signed-off-by: Mat Booth <mat.booth@redhat.com>

Make the requirement on "osgi.serviceloader.registrar" optional

---

jetty-security/src/main/java/org/eclipse/jetty/security/HashLoginService.java
jetty-security/src/main/java/org/eclipse/jetty/security/PropertyUserStore.java
jetty-security/src/main/java/org/eclipse/jetty/security/UserStore.java
jetty-security/src/test/java/org/eclipse/jetty/security/TestLoginService.java
jetty-security/src/test/java/org/eclipse/jetty/security/UserStoreTest.java
pom.xml

Add convenient method to add user to Realm 

---

jetty-quickstart/src/test/java/org/eclipse/jetty/quickstart/TestQuickStart.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/Invoker.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletHandlerTest.java

@joakime We could refactor `ServletHandler` like this to better support your use-case of adding regex mapping support (specially as `PathSpec` already has a regex variant).  Can you evaluate if this works for your use-case.
Note that for servlet 4.0, we will need to carry the MappedResource<ServletHolder> entry with the request so that we will be able to generate the new https://github.com/javaee/javax.servlet/blob/master/src/main/java/javax/servlet/http/ServletMapping.java instance

Refactor ServletHandler to add getMappedServlet method

---

jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationConfiguration.java
jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java
jetty-annotations/src/main/java/org/eclipse/jetty/annotations/ClassInheritanceHandler.java
jetty-annotations/src/test/java/org/eclipse/jetty/annotations/TestAnnotationInheritance.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpConnectionOverHTTP2.java
jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/annotations/AnnotationParser.java
jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/ContainerInitializer.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
jetty-util/src/main/java/org/eclipse/jetty/util/ConcurrentHashSet.java
jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/CachingWebAppClassLoader.java

Hey,
since Java 8 there is `ConcurrentHashMap.newKeySet()` which effectively replaces Jetty's custom ConcurrentHashSet. The following PR replaces occurences of `new ConcurrentHashSet()` with the built-in one and deprecates ConcurrentHashSet.
Let me know what you think.
Cheers,
Christoph

Deprecate ConcurrentHashSet

---

jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java

The result of `toString()` is expected to be the path name of a Resource. This is used for determining the mime type based on the file name extension in `org.eclipse.jetty.server.ResourceCache.Content`. Without a custom `toString()` implementation, no mime type can be determined for a resource. This problem does no longer exist in current Jetty, since `PathResource` has vanished.

Fix determining mime type of `PathResource` based on the file name in Jetty 9.2.

---

jetty-home/src/main/resources/bin/jetty.sh

We've had some issues where our servlets would take more than 1 minute to launch.
Here's a pull request to configure the timeout.
Signed-off-by: Zachary Duquette <zachary.duquette@eidosmontreal.com>

Configure jetty start timeout using JETTY_START_TIMEOUT

---

jetty-home/src/main/resources/bin/jetty.sh

A coworker pointed out there was a warning that I overlooked.
Signed-off-by: Zachary Duquette <zachary.duquette@eidosmontreal.com>

Added missing space to remove bash warning from JETTY_START_TIMEOUT

---

jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java

WebSocketClient automatically registers itself with a ShutdownThread which ensures cleanup when the JVM terminates. However, this prevents an application from managing JVM shutdown with open websockets.
This adds a new method to WebSocketClient, `setStopAtShutdown(boolean)`, which defaults to true to preserve existing behavior. This imitates the setStopAtShutdown logic in the jetty server.

Allow for configuring WebSocketClient JVM lifecycle

---

jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java
jetty-servlets/src/test/java/org/eclipse/jetty/servlets/DoSFilterTest.java
jetty-servlets/src/test/java/org/eclipse/jetty/servlets/mocks/MockFilterConfig.java
jetty-servlets/src/test/java/org/eclipse/jetty/servlets/mocks/MockHttpServletRequest.java

RemotePort tracking feature of DosFilter tracker now has address and port delimited with a colon to avoid rare collisions by just concatenating them together

Issues #1717 DoSFilter remotePort tracker loadId delimiter added

---

jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
jetty-server/src/main/config/etc/jetty-connectionlimit.xml
jetty-server/src/main/config/modules/connectionlimit.mod
jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionLimit.java
jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java
jetty-server/src/test/java/org/eclipse/jetty/server/LowResourcesMonitorTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/NotAcceptingTest.java

I had previously added the setAccepting(boolean) mechanism on the connectors.
This is a mechanism to trigger this by monitoring the total number of connections on the server.
I'm not 100% sure I like the approach, other options include:
- a limit per connector rather than server wide (this one can be used like that but not with current mod file)
- add a limit to the existing connector stats listener
- use the low resources monitor to poll the connector stats listener for the number of connections
Feedback wanted

Issue #1732 Connection Limit

---

jetty-home/src/main/resources/bin/jetty.service

This pull request adds the systemd service file, it relies on the systemv init script.
Don't forget to run:
echo "JETTY_PID=/opt/web/mybase/jetty.pid" >> /etc/default/jetty
This documentation should be updated:
http://www.eclipse.org/jetty/documentation/current/startup-unix-service.html#_practical_setup_of_a_jetty_service

Add systemd service file #1485

---

jetty-bom/pom.xml

jetty-monitor is not build anymore. Not sure if we need to keep it in the bom?

fix some Maven artifact coordinates in the bom

---

jetty-documentation/src/main/asciidoc/administration/http2/configuring-http2.adoc

The http2 documentation and the code do not agree on the default maximum concurrent streams per connection. The documentation has been updated to reflect the code's default value of 128. See line 48:

correct value of max streams per http2 connection

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractModifyMaxInactiveIntervalTest.java

Session.getMaxInactiveInterval should return a negative number if the
the session is configured with a negative maxInactiveInterval. It was
being rounded up to 0 by mistake.
Signed-off-by: Dan Smith <upthewaterspout@apache.org>

Issue #1885 Fixed rounding error of negative maxInactiveInterval

---

jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java

> Comparison of expectation values is case-insensitive for unquoted tokens (including the 100-continue token), and is case-sensitive for quoted-string expectation-extensions.

proxy: case insensitive compare of Expect: 100-continue header

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/ReservedThreadExecutorTest.java

A NPE was observed from the ReservedThreadPool, that indicated a null thread was being used.  While I was unable to reproduce, it appears a race between stopping and using the last reserved thread.

Fix NPE when stopping with no resesrved threads

---

jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java

Fix for #1939 fair selector choice
An atomic integer is not used for the rolling candidate and a simple size comparison used to pick the smaller of the two candidates.

Issue #1939 fair selector choice

---

jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java
jetty-util/src/main/java/org/eclipse/jetty/util/MultiReleaseJarFile.java

Made MultiReleaseJarFile closeable and using try-with-resources in
AnnotationParser to avoid leaking file descriptors.
Made few code simplifications.

Issue #1797 - JEP 238 - Multi-Release JAR files break bytecode scanning.

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java

While testing #1961 for #1958,  it was noticed that blocking waits do not handle spurious wakeups.
This is a proposed change to handle spurious wakeups, but it is causing problems with
`org.eclipse.jetty.client.ssl.SslBytesServerTest.testRequestWithBigContentWithSplitBoundary()`.

Issue #1958 Blocking timeout spurious wakeups

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java

HttpParser is not using cached HTTP Field values

HttpParser is not using cached HTTP Field values

---

jetty-security/src/main/java/org/eclipse/jetty/security/authentication/FormAuthenticator.java
jetty-security/src/test/java/org/eclipse/jetty/security/ConstraintTest.java

We have a HTTP end-point with jetty-server which supports both Basic Authentication and Form Based Authentication.
We have a client which does XML-RPC over HTTP (Apache XML-RPC) and does not store state in the server session. In fact it completely ignores any cookies (e.g. `JSESSIONID`) sent by the server.
We have found an issue in `org.eclipse.jetty.security.authentication.FormAuthenticator` where even if it is enabled but form authentication is not requested by the client, then it creates a `HttpSession` anyway. As the client is stateless, this causes Jetty to create a new HTTP Session on the server for every single HTTP request from the client. Obviously this is not desirable, as this causes a lot of memory overhead on the server, (although this is eventually cleaned up when the …

Remove unnecessary session creation in FormAuthenticator

---

jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl-distribution.adoc
jetty-home/src/main/resources/modules/conscrypt.mod

Updated references to Conscrypt 1.0.0.RC11.
Used "default" rather than "native" for the JSSE docs.
Changed "two-way authentication" to "client certificate authentication".

Issue 1830 - Document Conscrypt SSL

---

jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java

CreateEndPoint and DestroyEndPoint are now submitted directly to
the Executor, rather than being submitted as selector actions.

Issue #2003 - Do not submit blocking tasks as managed selector actions.

---

jetty-server/src/main/java/org/eclipse/jetty/server/AbstractNCSARequestLog.java

Issue #1614 made authentication extensible in request log
Replaces #1620 for #1614.
Motivated by contribution from Meang Akira Tanaka <meang.tnk@gmail.com>

Issue #1614 made authentication extensible in request log

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletIOTest.java

Fix for #2006 isReady fails to register read interest
The problem was during a window between when we entered `ASYNC_WOKEN` state, but before the woken thread arrived in `HttpChannel.handle`.  If during that window, another thread "stole" the data data by reading it, then there would be no data available once the thread arrived in handle.  It was correctly not calling `onDataAvailable`, but incorrectly not registering for read interest after doing nothing

#2006 Use a NOOP to allow unhandle to cope with stolen read

---

jetty-alpn/jetty-alpn-client/pom.xml
jetty-alpn/jetty-alpn-openjdk8-client/pom.xml
jetty-alpn/jetty-alpn-openjdk8-server/pom.xml
jetty-alpn/jetty-alpn-server/pom.xml
jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-alpn.xml
jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-http2.xml
jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-https.xml
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJsp.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java

This PR adds the correct osgi headers for the openjdk8 alpn server and client modules. It also adds a proper test of using http2 in osgi.

Jetty 9.4.x 2016 openjdk8 osgi headers

---

jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java

Issue #2010 Support FIPs Key Managers, by only wrapping the default Key Manager if we have wildcard CN's or more than 1 non wild CN.  FIPs users will need to install a
keystore than has no multiple certificates than can only be resolved by SNI. They will also need to have no certificate aliases.

Issue #2010 Support FIPs Key Managers

---

jetty-client/pom.xml
jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
jetty-client/src/main/java/org/eclipse/jetty/client/jmx/HttpClientMBean.java
jetty-client/src/test/java/org/eclipse/jetty/client/jmx/HttpClientJMXTest.java

Added HttpClientMBean, and overridden getObjectContextBasis() so that
the HttpClient name is inherited by children components such as the
HttpClientTransport, the ThreadPool, etc.

Fixes #2020 - Introduce a name for `HttpClient` instances.

---

jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
jetty-client/src/main/java/org/eclipse/jetty/client/api/ContentProvider.java
jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java
jetty-client/src/main/java/org/eclipse/jetty/client/util/BytesContentProvider.java
jetty-client/src/main/java/org/eclipse/jetty/client/util/PathContentProvider.java
jetty-client/src/test/java/org/eclipse/jetty/client/AbstractHttpClientServerTest.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientAuthenticationTest.java

Introduced ContentProvider.isRepeatable() to detect whether the
request content can be provided more than once, and modified
ContentProvider implementation accordingly.
Modified AuthenticationProtocolHandler to not send an authenticated
request if the content is not repeatable.
Modified AuthenticationProtocolHandler to tolerate request failures.

Fixes #1949 - Client-side problems with digest authentication.

---

jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTimeoutTest.java
jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpChannelOverHTTP2.java
jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
jetty-server/src/test/java/org/eclipse/jetty/server/ConnectorTimeoutTest.java
jetty-websocket/websocket-client/src/test/java/org/eclipse/jetty/websocket/client/ClientCloseTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/ServerTimeoutsTest.java

This is a fix for HTTP/1 for #2081 
Delegate the readtimeout handling to HttpChannel so that a delayed dispatch can be ended.
A test harness is needed and we also need to consider if HTTP/2 & FCGI need similar fixes....

Issue #2081 No idle timeout exception when dispatch is delayed

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpSender.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpChannelOverHTTP2.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpConnectionOverHTTP2.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2Test.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpChannelAssociationTest.java

Removed the distinction between pushed and non-pushed channels; only
non-pushed channels are released and recycled if they're not failed.
Properly resetting HttpReceiverOverHTTP2.

Fixes #2088 - Recycle HTTP/2 channels on the client.

---

jetty-client/src/test/java/org/eclipse/jetty/client/LivelockTest.java
jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java
jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
jetty-io/src/test/java/org/eclipse/jetty/io/SelectorManagerTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/GracefulStopTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java

This is a second attempt at fixing #2046 
Commit 337eb97 cleaned up the whole selector action (now update) mechanism that had gotten a little too complex.
Commit 85e3647 updated the abstract lifecycle to prevent exceptions terminating a doStop or destroy loop.
Commit 56b0a54 addresses #2046 by:
- SelectorManager now tries to stop it's ManagedSelectors in parallel to avoid multiplying graceful stop timeout. This is still flawed, but is better than we had before.
- ManagedSelector.doStop will now always wait at least 1s to try to stop the selector, even if not graceful.  If the timeout expires, then it aborts any stopping in progress and does a forced stop, which does not call any listeners etc.   I think this is a reasonable approach, but I don't like the arbitrary 1s wait.

Issue #2046 - Graceful stop of connections

---

pom.xml

This updates to jasper 8.5.24.  Note that the 8.5.24.1 updated mortbay jsp jars will have an Automatic-Module-Name header in their manifests that resolves #2123 too.

Issue #2079 Update to Jasper 8.5.24

---

jetty-deploy/src/main/java/org/eclipse/jetty/deploy/AppLifeCycle.java
jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentManager.java
jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/StandardStarter.java
jetty-plus/src/main/java/org/eclipse/jetty/plus/webapp/EnvConfiguration.java
jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/DeploymentErrorInitializer.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/DeploymentErrorTest.java
tests/test-integration/src/test/resources/docroots/deployerror/badapp-unavailable-false.xml
tests/test-integration/src/test/resources/docroots/deployerror/badapp.xml
tests/test-integration/src/test/resources/docroots/deployerror/badapp/WEB-INF/classes/META-INF/services/javax.servlet.ServletContainerInitializer
tests/test-integration/src/test/resources/docroots/deployerror/badapp/WEB-INF/web.xml

Fixes deployment errors that occur during WebAppContext.doStart() to respond on Throwable, not Exception.  Allowing for a fast fail of the deployment and not running subsequent configurations and or SCI's if one fails.

Issue #1602 - Deployment Error should fail fast

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java

`QueuedThreadPool` constructor validation for min vs max threads to prevent silent configuration failures. Unlike setters, the constructors have both values in one method call so we can check for incorrect argument ordering (e.g. broken configuration management).
The test is much more involved than the implementation, using reflection to find relevant `QTP` constructors. If that's not ok, then I'm fine deleting the test since the new constructor logic is so straightforward. Let me know, and I'll update.

qtp constructor min-max validation

---

Jenkinsfile

ATM we only build with jdk8 and have a separate build for jdk9 so it means pr are not build with jdk9 (so we usually verify pr or branches with jdk9 after merge)
This pr will simply build the project with jdk9 as well (in parallel)

add multiple jdks build

---

jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyDeployWar.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarExplodedMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStartMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java

A change that came in with commit https://github.com/eclipse/jetty.project/commit/4b513c61e8ac7400826880d18729c71eca1b6ae8#diff-28ee2c02100a8cae9e1d1754ea32af10R64 meant that the deploy-war goal was now insisting that the project was of packaging type war, which was not the intention.
I've reviewed all of the goals, and implemented a check for packaging war only on these:
run
run-war
run-exploded
run-forked
run-distro
effective-web-xml
These other goals do not require packaging war:
start
stop
deploy-war

Issue #2209 Require war packaging only for some jetty maven plugin goals

---

jetty-util/src/main/java/org/eclipse/jetty/util/B64Code.java
jetty-util/src/main/java/org/eclipse/jetty/util/security/UnixCrypt.java

Ignored warning in B64Code
US-ASCII in UnixCrypt
#2206

Resolved default charset warning in jetty-util for #2206

---

pom.xml

brackets can be used optionally for clarity but aren't manditory #2206

Disabled errorprone OperatorPrecedence warnings #2206

---

jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWebAppAsService.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithAnnotations.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJsp.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithWebSocket.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java

The problem was that the tests were trying to pick an unused port for the ssl tests, but by the time the selector tried to use the port, the port had been taken by another test.  I've changed the tests so that they use a value of jetty.ssl.port=0, which causes the ServerConnector to randomly assign and use a port in the one action.

Issue #2247 Ensure random unused ssl port for osgi tests

---

jetty-osgi/test-jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-http2-jdk9.xml
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
pom.xml

Makes appropriate tests work in jdk9, plus adds a test for the alpn-java-server/client.

Jetty 9.4.x 2059 make osgi tests work jre9

---

jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java
jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java
jetty-http2/http2-http-client-transport/src/test/resources/jetty-logging.properties
jetty-util/src/main/java/org/eclipse/jetty/util/AtomicBiInteger.java
jetty-util/src/test/java/org/eclipse/jetty/util/AtomicBiIntegerTest.java

For #2293
Added a AtomicBiInteger to allow both total connections and pending connections to be encoded in the same atomic int.
Calculate maxPending connections and make tryCreate respect it

Jetty 9.4.x 2293 pending multiplexed

---

jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java
jetty-fcgi/fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/ServerFCGIConnection.java
jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerHTTPTest.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpTester.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpChannelOverHTTP2.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java
jetty-server/src/main/java/org/eclipse/jetty/server/LocalConnector.java

Changed the signature of HttpParser.Listener.onBadMessage()
to take a BadMessageException and updated dependent code.

Fixes #2318 - HttpParser.Listener.onBadMessage() should take BadMessageException

---

jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java

+ Added testcase to replicate
+ Making character encoding from unset during sendError

Issue #2307 - On sendError() the response character encoding is null

---

jetty-client/src/test/java/org/eclipse/jetty/client/LivelockTest.java
jetty-client/src/test/resources/jetty-logging.properties
jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java

Issue #2218 - Windows Selector Bug

---

jetty-util/src/main/java/org/eclipse/jetty/util/JavaVersion.java
jetty-util/src/test/java/org/eclipse/jetty/util/JavaVersionTest.java

For #2284 no longer parse the optional detail of the java version.
Parse failures will result in a guessed JVM platform 8

Safer simpler version parsing #2284

---

jetty-distribution/pom.xml
pom.xml
tests/test-integration/pom.xml

- Speculative fix to ensure that the users of the jetty-distribution
do not require the test artifacts to utilize the tarball / zip files
- Also disabled the snapshot repository as it causes false success

Issue #2278 - making distribution pom not require tests

---

jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2Test.java

Now exiting the parse loop when the response is complete; if there
are bytes remaining in the buffer, then it's cleared out.

Fixes #2311 - TimeoutException when server sends unexpected content.

---

jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/CloseState.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/IStream.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/EmptyServerHandler.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/MaxConcurrentStreamsTest.java

Changed the max concurrent remote streams enforcement algorithm.
It is now based on the stream count and the closing stream count,
updated atomically in a state machine in HTTP2Stream.

Issue #2349 - Review HTTP/2 max streams enforcement.

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java

+ Flag existing methods / fields as deprecated
+ Indicate removal in Jetty 10.x

Issue #987 - move checkGzExists default to false

---

jetty-http2/http2-common/pom.xml
jetty-memcached/jetty-memcached-sessions/pom.xml
jetty-plus/pom.xml
jetty-security/pom.xml
jetty-websocket/pom.xml
pom.xml
tests/test-webapps/test-servlet-spec/test-spec-webapp/pom.xml

Change the defaults for our osgi header generation to remove warnings about unused imports and exports.

Issue #2109 remove warnings for unused imports and exports

---

jetty-util/src/main/java/org/eclipse/jetty/util/Jetty.java

Example output:
JDK 8:
2018-04-04 22:30:25.578:INFO:oejs.Server:main: jetty-9.4.10-SNAPSHOT; built: 2018-04-04T22:22:03.202Z; git: 2b32f82aeb64acc6105c08d8a7a141279f8b91d0; jvm 1.8.0_131-b11
JDK 9:
2018-04-04 22:29:39.035:INFO:oejs.Server:main: jetty-9.4.10-SNAPSHOT; built: 2018-04-04T22:22:03.202Z; git: 2b32f82aeb64acc6105c08d8a7a141279f8b91d0; jvm 9+181
JDK 10:
2018-04-04 17:29:07.568:INFO:oejs.Server:main: jetty-9.4.10-SNAPSHOT; built: 2018-04-04T22:22:03.202Z; git: 2b32f82aeb64acc6105c08d8a7a141279f8b91d0; jvm 10+46

Issue #2413 - Using Instant.toString() to be consistent with timestamp

---

jetty-server/src/main/java/org/eclipse/jetty/server/CachedContentFactory.java
jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
jetty-util/src/test/java/org/eclipse/jetty/util/BufferUtilTest.java

Now explicitly using a _mappedBuffer field in
CachedContentFactory.CachedHttpContent.
Deprecated BufferUtil.isMappedBuffer().

Fixes #2425 - Review BufferUtil.isMappedBuffer().

---

jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java

Changed regex for AUTHENTICATE_PATTERN so that the realm doesn't need to appear as first parameter. #1555

Issue #1555 WWW-Authenticate realm header ordering

---

apache-jsp/pom.xml
jetty-alpn/jetty-alpn-client/pom.xml
jetty-alpn/jetty-alpn-conscrypt-client/pom.xml
jetty-alpn/jetty-alpn-conscrypt-server/pom.xml
jetty-alpn/jetty-alpn-java-client/pom.xml
jetty-alpn/jetty-alpn-java-server/pom.xml
jetty-alpn/jetty-alpn-openjdk8-client/pom.xml
jetty-alpn/jetty-alpn-openjdk8-server/pom.xml
jetty-alpn/jetty-alpn-server/pom.xml
jetty-annotations/pom.xml
jetty-http-spi/pom.xml
jetty-http/pom.xml
jetty-http2/http2-hpack/pom.xml
jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/JettyBootstrapActivator.java
jetty-spring/pom.xml
jetty-websocket/javax-websocket-client-impl/pom.xml
jetty-websocket/javax-websocket-server-impl/pom.xml
jetty-websocket/websocket-api/pom.xml
jetty-websocket/websocket-common/pom.xml
jetty-websocket/websocket-server/pom.xml
jetty-websocket/websocket-servlet/pom.xml

This PR is following on from the discussion in #2164 and PR #2377.
In PR #2377 it is apparent that there are some use-cases where jetty is deployed into an osgi container where the osgi.serviceloader capability is not present (eg SpiFly is not deployed).  Although jetty uses the java.util.ServiceLoader more and more, there are usecases that avoid invoking code in a bundle that uses the ServiceLoader. Therefore, making the osgi.serviceloader.processor and osgi.serviceloader.registrar mandatory breaks those use cases.
The solution adopted is to always make the osgi.serviceloader.processor/registrar requirement resolution=optional, but in the jetty-boot bundle print out a warning if we can detect that it is not present.

Issue #2164 Make osgi.serviceloader mostly optional

---

jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/InvalidServerTest.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java

Fixed by start reading from the server after the session
promise has been notified, which may send the first request.

Issue #2474 - HTTP/2 client not handling invalid servers correctly.

---

jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
jetty-client/src/main/java/org/eclipse/jetty/client/api/Authentication.java
jetty-client/src/main/java/org/eclipse/jetty/client/util/DigestAuthentication.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientAuthenticationTest.java

Reworked the way authentication parameters are parsed to make them order independent and to allow allow for a missing realm parameter. This also prevents parsing over the parameters twice.
#1555 
- Removed the regex to separate out the realm parameter and instead parse it with the other parameters into HeaderInfo.
- Changed HeaderInfo to store the parsed parameters as a Map instead of the un-parsed parameters in a string.
- The parsing of the parameters is now done in AuthenticationProtocolHandler.newHeaderInfo(String) and then passed into the HeaderInfo instead of Parsing it in DigestAuthentication.
- Replaced the usage of splitParams(String) with QuotedCSV used to parse the parameters.
- Added test to check the ordering of parameters doesn't matter.
- Allow not to have a realm …

Jetty 9.4.x #1555 wwwAuthenticate Parsing

---

jetty-http/src/main/java/org/eclipse/jetty/http/PreEncodedHttpField.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldTest.java

Which might happen when given `HttpHeader` is null. It might be null when most generic constructor `#PreEncodedHttpField(HttpHeader, String, String)` is invoked with a null argument or when `#PreEncodedHttpField(String, String)` constructor is used. Later is valuable for custom headers. NPE happens because of an attempt to call `HttpHeader#asString()` on a null argument.
This PR fixes the problem by making encoders use specified header name, instead of trying to retrieve it from the `HttpHeader` object.
Signed-off-by: lutovich <konstantin.lutovich@neo4j.com>

Fix NPE in PreEncodedHttpField constructor

---

jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java

Due to shift operations taking less precedence over addition the expression was parsed in an unintended way.
With this change the intention is made more clear and the intended order of calculations (shift the single byte values into some variable) is actually implemented.

Fix operator priority in ProxyConnectionFactory

---

jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java

`AsyncMiddleManServlet.Transparent` class should extend `AsyncMiddleManServlet`
so the consumers can override the `newServerResponseContentTransformer` &
`newServerResponseContentTransformer` to provide their own ContentTransformer.
The way it is structured right now makes it impossible to use
`AsyncMiddleManServlet.Transparent` servlet as a middle man servlet.
Signed-off-by: Assim Deodia <assim.deodia@gmail.com>

AsyncMiddleManServlet.Transparent class wrongly extends ProxyServlet

---

tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredInvalidationSessionTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredOrphanedSessionTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredSessionScavengingTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestContextScopeListener.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/CreationTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DeleteUnloadableSessionTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DirtyAttributeTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/ModifyMaxInactiveIntervalTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/NonClusteredSessionScavengingTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/ReentrantRequestSessionTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SameContextForwardedSessionTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SaveOptimizeTest.java

Fixes a timing problem in session CreationTest, and applies the same fix in other tests that could potentially suffer from similar problem.  Also fixed a problem in the abstract test classes used for the various flavours of SessionDataStore tests, whereby SessionDataStoreFactories were being shared between different servers/contexts.

Issue #2274 Fix timing in CreationTest and other fixes

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java

+ Adding removeThread(Thread) to allow instrumentation
libraries to track removal of threads from Pool.

Issue #2498 - new QTP.removeThread(Thread) method

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/DefaultSessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/NullSessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/session/SessionCookieTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/IdleSessionTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/NullSessionCacheTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SameNodeLoadTest.java

Replace the session IdleTimeout with CyclicTimeout and start and stop the timer appropriately as requests leave and enter the session, and the session moves through its lifecycle.

Issue #2427 Stop and start session idle timer

---

jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/AttributeNormalizer.java
tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/AttributeNormalizerTest.java
tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/AttributeNormalizer_ToCanonicalUriTest.java

Fix #2446 by only stripping trailing '/' from non-root URIs.  

Support root base or home for quickstart #2446

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/handler/ContextHandlerTest.java

Allows for combined virtualhost@connectorname format when specifying virtualhosts. This format will only match if both the hostname AND connector name match. Currently if you specify a connector name in a list of virtualhosts it will always match if that connector matches regardless of the hostname. This change is backwards compatible with existing functionality and if you select just "@connectorname" then any hostname will match as long as the connector does.
This change would allow for a context to match if the connector is https or the connector is http and localhost only for example

Issue #1785 Added vhost@connectorname format for AND behavior

---

jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java

Issue #2549 ConsumeAll forced EOF or EarlyEOF
It is not clear how the input stream can be left in STREAM state by the time `Request.recycle()` is called.   So this is a defensive change to force an  EOF state while we do more investigation.  This does not close #2549

Issue #2549 ConsumeAll forced EOF or EarlyEOF

---

jetty-server/src/test/java/org/eclipse/jetty/server/ConnectorTimeoutTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java

fixes some exception stack traces that were being printed out while running the jetty-server tests
closes #2542 
closes #2424

jetty-server exception stack traces

---

jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackContext.java
jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java
jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/MetaDataBuilder.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackDecoderTest.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackEncoderTest.java

#2571 When an entry that is too large for the dynamic table is added, the entire table should be evicted as per the RFC. Previously we were throwing a 431 Bad Message.   This will require that the OP should retest #1134.

Issue #2571 HPACK table overflow

---

jetty-util/src/main/java/org/eclipse/jetty/util/MultiException.java
jetty-util/src/test/java/org/eclipse/jetty/util/MultiExceptionTest.java

This doesn't actually stop creating the unnecessary exception instead it
stops running the expensive `fillInStackTrace()` unless we actually need
it.
This does result in the stack trace being set to where we throw the
exception rather than when we create it.
Signed-off-by: Luke Butters <lbutters@funnelback.com>

Stop creating unnecessary exceptions with MultiException #2580

---

jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletIOTest.java

By only testing for contains 0, it left open the possibility that the start of a chunk containing a 0 eg '10' might arrive before the write is blocked and async.complete is called.

Issue #2599 Fix AsyncServletIOTest

---

jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpTrailersTest.java

Trailer handling was erroneously firing the response success event
before all the response content events happened.
Now the trailer handling uses a poison-pill DATA frame to make sure that
all response content events happen before the response success event.

Fixes #2616 - Trailers preventing client from processing all the data.

---

jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
jetty-io/src/test/java/org/eclipse/jetty/io/SslConnectionTest.java
jetty-server/src/main/java/org/eclipse/jetty/server/SslConnectionFactory.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/io/WebSocketClientSelectorManager.java

Allow the Direct ByteBuffer usage to be configurable at the SslConnectionFactory level for benefit of Android 8.1+ users.

Issue #2135 - proposal for Android 8.1 with SSL and direct buffers

---

jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-running.adoc

changed % to $ in the example of --list-config command
Signed-off-by: Jameson Allen <jameson.f.allen@gmail.com>

Incorrect sigil used for example of --list-config command

---

jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
jetty-io/src/test/java/org/eclipse/jetty/io/WriteFlusherTest.java

**Rework of WriteFlusher**
WriteFlusher.write() now requires the callback it is given is not null
the FAILED state of WriteFlusher is now a terminal state
any failure will now result in the callback being failed and a transition to the FAILED state
the WriteFlusher documentation and WriteFlusherTests have also been altered to reflect these changes

Issue #2592 - WriteFlusher Cleanup

---

jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationConfiguration.java
jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java
jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/ProxyTest.java
jetty-infinispan/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataStore.java
jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/BaseAuthModule.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ProxyServletTest.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/DigestAuthenticator.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/FormAuthenticator.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/AbstractHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/AsyncRequestReadTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/ExtendedServerTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SSLEngineTest.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/StatisticsServlet.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncContextTest.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletIOTest.java
jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java
jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushSessionCacheFilter.java
jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/TestFileInitializer.java
jetty-util/src/main/java/org/eclipse/jetty/util/IPAddressMap.java
jetty-util/src/main/java/org/eclipse/jetty/util/MultiReleaseJarFile.java
jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/strategy/jmh/TestConnection.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java
jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/extensions/ExtensionConfig.java

Removed some unnecessary conversions from primitive to boxed types.
For finding them in Eclipse, I activated warnings for "Boxing and unboxing conversions", filtered for those in the "Problems" view, and quickly went through them.

Issue #2662 "Unnecessary boxing conversions"

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandlerCollection.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/HandlerCollection.java

Just a minor improvement to avoid calling `HandlerCollection.getHandlers()` more often than needed within the same method.

Eliminated redundant invocations of HandlerCollection.getHandlers()

---

jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java

Improved defaulting values for the truststore, avoiding to default
the password, which is often missing for a truststore.

Issue #901 - Overriding SSL context KeyStoreType requires explicit override of TrustStoreType.

---

jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-connectors.adoc
jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java
jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
jetty-server/src/main/config/etc/jetty-acceptratelimit.xml
jetty-server/src/main/config/etc/jetty-connectionlimit.xml
jetty-server/src/main/config/modules/acceptratelimit.mod
jetty-server/src/main/config/modules/connectionlimit.mod
jetty-server/src/main/java/org/eclipse/jetty/server/AcceptRateLimit.java
jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionLimit.java
jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java
jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java
jetty-server/src/test/java/org/eclipse/jetty/server/NotAcceptingTest.java
jetty-server/src/test/resources/jetty-logging.properties
jetty-util/src/main/java/org/eclipse/jetty/util/statistic/RateStatistic.java
jetty-util/src/test/java/org/eclipse/jetty/util/statistic/CounterStatisticTest.java
jetty-util/src/test/java/org/eclipse/jetty/util/statistic/RateStatisticTest.java

For #2501 we now include accepting connections in the `ConnectionLimit` handling (which is event based), but not in the `LowResourcesMonitor` (which is poll based).
Setting a connection limit on `LowResourcesMonitor` is now deprecated and sets a warning... as it was never really thorough anyway being poll based.
`ConnectionLimit` can now also set an idletimeout for established connections.
This should protect against large numbers of connection, but is currently not a lot of help in diagnosing them.

Jetty 9.4.x 2501 accept listener

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java

the HttpFields being added to the CACHE in lines 232-236
are already being added in the previous loop
https://github.com/eclipse/jetty.project/blob/c45ca9e38bf7f8beaba1dd45e361fae6d8e2962a/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java#L228-L230

Removing unnecessary CACHE.put calls in HttpParser

---

jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java

#2530: after discussion on openjdk/nio-dev, we now wakeup the selector
after closing a socket, so that the SelectionKey can be removed
from the Selector and the TCP stack notified that the socket
has been really closed, so that it can send RST to clients.

Fixes #2530 - Client waits forever for cancelled uploads.

---

jetty-websocket/websocket-servlet/pom.xml

Closes #2694
Fixes the dynamic imports of `org.eclipse.jetty.websocket.server` and `org.eclipse.jetty.websocket.server.pathmap` as explained in the issue #2694 proposition 2. (previously the content of `org.eclipse.jetty.websocket.server` was not imported)
Signed-off-by: Clément Delgrange <cl.delgrange@protonmail.com>

Fixes #2694 - Dynamic imports of Websocket servlet

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/handler/StatisticsHandlerTest.java

#2717.
Now using _requestStats instead of _dispatchedStats to check for
requests completed when shutting down StatisticsHandler.

Fixes #2717 - Async requests are not considered when shutting down gracefully.

---

jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2Client.java
jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/MaxPushedStreamsTest.java

Issue #2730.
Using the same mechanism we use to limit max concurrent streams.

Fixes #2730 - Limit concurrent HTTP/2 pushed resources.

---

jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/Huffman.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackContextTest.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackDecoderTest.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HuffmanTest.java

#2679 and #2695
throw StreamException if huffman encoded string has:
- more than 7 bits of padding
- is padded by 0's and not 1's 
- has a string literal representation containing the EOS symbol

Issue #2679 - h2spec compliance Huffman encoding

---

jetty-home/src/main/resources/bin/jetty.sh

Signed-off-by: David Shepherdson <david@shepherdson.name>

Issue #2762: Fixed typo when checking JETTY_START_TIMEOUT.

---

jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/ClientContainer.java
jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/JsrSession.java
jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/JettyEchoSocket.java
jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/LargeMessageTest.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/LargeClientContainerInitAsServerListener.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/LargeClientContainerServlet.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/LargeNestedClientContainerTest.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/LargeOnOpenSessionConfiguredTest.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/LargeServerContainerAsClientContainerServlet.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/WSServer.java
jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/samples/echo/LargeEchoAnnotatedSocket.java
jetty-websocket/javax-websocket-server-impl/src/test/resources/large-client-container-servlet-init-use-server-web.xml
jetty-websocket/javax-websocket-server-impl/src/test/resources/large-client-container-servlet-web.xml
jetty-websocket/javax-websocket-server-impl/src/test/resources/large-server-as-client-container-servlet-web.xml
jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/Parser.java

* Added Client unit tests for large messages
* Re-enabled Server unit tests for large messages
* Added more Server unit tests for large messages
* On JSR356 Client Container, using `WebSocketClient` as container delegate.
* On JSR356 Server with policy (and Behavior of SERVER), which is managing a `javax.websocker.server.ServerContainer`...
+ A user obtains a reference to that `ServerContainer` (via the ServletContext attributes)
+ User uses that `ServerContainer` to connect to a remote websocket endpoint using one of the `connectToServer()` methods found on the `ServerContainer` object (made available via the  `javax.websocket.WebSocketContainer` interface)
+ The policy used in this scenario is the `ServerContainer` policy, but is delegated down to the Client Container with a different …

Issue #2767 - WebSocket Policy on JSR356 ClientContainer not represented correctly

---

pom.xml

Create a profile, 'eclipse-sign', that is enabled when the property by
the same name is defined, in order to handle the signing of Eclipse
bundles by the configured signing service.
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

Issue #2639 - Add profile for jar signing with eclipse-jarsigner-plugin.

---

jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/JaspiAuthenticatorFactory.java

Removed the subject parameter from `findServerName(Server, Subject)` and instead use the previously unused Server parameter to find the subject using `findServiceSubject(server)`
contextPath String was not being used
added back a deprecated `findServerName(Server, Subject)` method with the previous signature which calls the new method 
closes #321

Issue #321 - jaspi authenticator factory dead code

---

pom.xml

Create a profile, 'eclipse-sign', that is enabled when the property by
the same name is defined, in order to handle the signing of Eclipse
bundles by the configured signing service.
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

Issue #2794 - Add profile for jar signing with eclipse-jarsigner-plugin.

---

jetty-server/src/main/config/etc/sessions/jdbc/datasource.xml
jetty-server/src/main/config/etc/sessions/jdbc/driver.xml
jetty-server/src/main/config/modules/session-store-jdbc.mod
jetty-server/src/main/java/org/eclipse/jetty/server/session/DatabaseAdaptor.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/JDBCSessionDataStore.java

Allow the type of string columns to be explicitly set, rather than hardcoded to "varchar". Also relax visibility restrictions on JDBCSessionDataStore methods, making them at least protected, to ease subclassing.

Jetty 9.4.x 2745 jdbcsessiondatastore nvarchar

---

jetty-plus/src/main/java/org/eclipse/jetty/plus/webapp/EnvConfiguration.java
tests/test-webapps/test-jndi-webapp/src/main/java/com/acme/JNDITest.java
tests/test-webapps/test-jndi-webapp/src/main/webapp/WEB-INF/jetty-env.xml

Ensure that the usual jetty properties eg Server, jetty.home, jetty.base are available for reference in jetty-env.xml files.

Issue #2720 Ensure standard jetty properties available in jetty-env.xml

---

jetty-jmh/pom.xml
jetty-jmh/src/main/java/org/eclipse/jetty/server/jmh/DeflaterPoolBenchmark.java
jetty-server/src/main/config/etc/jetty-gzip.xml
jetty-server/src/main/config/modules/gzip.mod
jetty-server/src/main/java/org/eclipse/jetty/server/DeflaterPool.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java

Removed the ThreadLocal pooling of deflaters in GzipHandler in favour of a new DeflaterPool class
GzipHttpOutputInterceptor.GzipBufferCB now recycles the Deflater in onCompleteFailure()
added benchmark for the DeflaterPool
#300

Issue #300 - Implement Deflater Pool

---

jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java

Issue #2824 - Request.getParameters() should not reparse or recreate _parameters Map

---

jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DispatcherTest.java

More for #2787
If a bad request query parameter is first decoded in a RequestDispatcher, then a BadMessage exception should be generated and a 400 results.
If a bad forward query parameter is decoded in a RequestDispatcher, then a 500 should result.

Issue #2787 BadMessage if bad query detected in dispatcher

---

jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java

WebAppProvider tries to use a File object constructed just from the name of a file that has been deleted: as the file is deleted, File.isDirectory() check cannot succeed.

Issue #2681 Hot undeploy dir deployments.

---

jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java

+ During WebInfConfiguration.unpack()
If you have WebAppContext declared with .setWar()
and it points to a file on the filesystem, use that
original PathResource object to determine lastModified()
instead of the forced JarFileResource.
This is done to avoid URLConnection caching that prevents
the original WAR file from being deleted / replaced on
MS Windows.

Issue #2835 - Use original WAR Resource for lastModified

---

jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java

Now HTTP/2 sessions are not added to the Jetty component tree,
but rather just held by HTTP2SessionContainer that is added to
the Jetty container tree at startup.
HTTP2SessionContainer uses a concurrent Set to hold HTTP/2 sessions
to have good add/remove performance.

Fixes #2828 - AbstractHTTP2ServerConnectionFactory concurrent connect low performance.

---

jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslSelectionDump.java
jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java

+ ensuring SLOTH fix still works with updated testcase
+ Dump detection of JreDisabled:java.security only checked
default SSLEngine.enabledCipherSuites
New implementation changes meaning to be more general
JVM:disabled (as in not selected by default), and
only reports it as disabled in the dump if not specifically
included from the SSLEngine.supportedCipherSuites via
the SslContextFactory.includedCipherSuites configuration

Issue #2811 - Dump fix JreDisabled:java.security to JVM:disabled

---

jetty-documentation/src/main/asciidoc/administration/extras/default-servlet.adoc
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java
jetty-webapp/src/main/config/etc/webdefault.xml
tests/test-webapps/test-jetty-webapp/src/main/config/demo-base/webapps/test.d/override-web.xml

Remove cruft from webdefault.xml, fix the xml comments for DefaultServlet declaration. Also fix doc for DefaultServlet. Also (re)enable serving of precompressed static content in the test webapp.

Issue #2844 Clean up webdefault and DefaultServlet documentation

---

jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/StreamResetTest.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java

HttpInput.consume() now checks if the state is already failed,
and if so it does not change it when consuming the input.

Issue #2871 - Server reads -1 after client resets HTTP/2 stream.

---

jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java

Change the log message in the case where there is no "Implementation-Version" in the manifest to be INFO rather than WARN (gets around a short-term problem with bad ASM manifest), and also convert the log messages to use the string "ASM6" instead of the integer representation.

Issue #2834 Make ASM version error message friendlier

---

jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/webapp/OSGiWebappClassLoader.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java

When the WebAppClassLoader changed in jetty-9.4 in commit https://github.com/eclipse/jetty.project/commit/afb750515e3f5bd2f3ebb7a84b5dc34f7cdcef6a#diff-2640580777fa432610309ad6bf8dedff  it meant that the OSGiWebappClassLoader was no longer always consulting the bundle classloader first.  This change ensures that the OSGiWebAppClassLoader integrates properly with the WebAppClassLoader, respecting all of the checks for system/server classes, yet uses the bundle classloader to actually load classes (where possible).

Issue #2740 Ensure OSGiWebappClassLoader uses bundleloader for all loadClass methods

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java

Issue #2913.
Replaced usage of sun.reflect.Reflection with a
SecurityManager subclass, so that it works in all JDKs.

Fixes #2913 - ClassNotFoundException: sun.reflect.Reflection with JDK 11

---

jetty-annotations/src/main/java/org/eclipse/jetty/annotations/WebListenerAnnotation.java
jetty-maven-plugin/pom.xml
jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartDescriptorGenerator.java
jetty-quickstart/src/test/java/org/eclipse/jetty/quickstart/TestQuickStart.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ListenerHolder.java
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java
pom.xml

Listener classes have been eagerly instantiated, however the instantiation should be delayed until  the class is going to be used. This avoids unnecessary load of the listener class during quickstart preparation.

Jetty 9.4.x 2903 delay listener instantiation

---

jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ErrorPageTest.java

The BadMessageException occurring during the process outlined in Issue #2936 was not able to be handled by an ErrorPageErrorHandler.
This PR changes the `Dispatcher.error()` and subsequent `Dispatcher.forward()` to be forgiving on the `Request.mergeQueryParameters()` failure only during ERROR dispatch behaviors.

Issue #2936 - BadMessageException should be able to be handled by ErrorPageErrorHandler

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpSender.java

Issue #859.
Now executing the call to abort() so that the stack overflow is avoided.

Fixes #859 - Stack overflow error in jetty high level API.

---

jetty-client/src/main/java/org/eclipse/jetty/client/AbstractHttpClientTransport.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpResponseException.java
jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
jetty-client/src/test/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTPTest.java
jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java

Issue #2954 report cause
This change has already mostly been made in 9.4, so essentially this is a back port.  However the
primary signature of HttpParser.Handler for badMessage has not been changed and a default method
used to handle the cause. This avoids breaking any usages of the interface.

Jetty 9.3.x #2954 report cause

---

jetty-util/src/main/java/org/eclipse/jetty/util/security/Credential.java
jetty-util/src/test/java/org/eclipse/jetty/util/security/CredentialTest.java

fixes ArithmeticException in Credential.stringEquals and .byteEquals when given empty known string
Closes #2702

Issue #2702 - ArithmeticException in Credential.stringEquals and .byteEquals

---

jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java
jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTest.java

This change adds context information when BindExceptions are thrown, so that users who see the stack trace know which port it was that the application attempted to bind (which in a complex deployment may not be obvious).

Improve error message when binding to in-use port

---

jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormDataCompliance.java
jetty-http/src/main/java/org/eclipse/jetty/http/internal/MultiPartInputStreamParser.java
jetty-http/src/main/java/org/eclipse/jetty/http/internal/ReadLineInputStream.java
jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartCaptureTest.java
jetty-http/src/test/java/org/eclipse/jetty/http/internal/MultiPartInputStreamParserTest.java
jetty-http/src/test/java/org/eclipse/jetty/http/internal/ReadLineInputStreamTest.java
jetty-jmh/src/main/java/org/eclipse/jetty/http/jmh/MultiPartBenchmark.java
jetty-server/src/main/config/etc/jetty.xml
jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
jetty-server/src/main/java/org/eclipse/jetty/server/MultiParts.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
jetty-servlets/src/main/java/org/eclipse/jetty/servlets/MultiPartFilter.java
jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java

+ Moving MultiPartInputStreamParser from jetty-util to jetty-http/internal
+ Moving related classes ReadLineInputStream to jetty-http/internal
+ Moving MultiPartFormDataCompliance to jetty-http (next to the other Compliance modes)
+ Moving related tests to jetty-http as well
+ Renaming test to have same name as implementation

Issue #3010 - Move old MultiPart to jetty-http

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java

Implement suggestion by @gregw for logging initial scope entry for DebugListener. See issue #294 for details.

Issue #294 Initial enter scope for DebugListener

---

jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ListenerHolder.java

The previous fix for #2903 has a trivial bug, that was not revealed until testing for #294.

Issue #2903 Fix ListenerHolder.setListener

---

jetty-server/src/main/java/org/eclipse/jetty/server/CookieCutter.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutterTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutter_LenientTest.java

For #3041 allow commas as a cookie separator in RFC2965 compliance mode.

Allows commas to separate cookies in RFC2965 compliance mode

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java

Used the session from the BaseRequest when calling complete from the SessionAsyncListener. Also removed the session argument to SessionAsyncListener constructor as it is never used.

Issue #3044 Use unwrapped session for SessionAsyncListener

---

Jenkinsfile

Issue #3051 - New Simplified Jenkinsfile

---

jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/Huffman.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackTest.java
jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HuffmanTest.java
jetty-jmh/src/main/java/org/eclipse/jetty/io/jmh/ByteBufferBenchmark.java

Testing indicates that there is no longer any performance advantage to using arrays to access byte buffer, so this PR adds direct buffer support to HPACK so HTTP2 can use direct buffers

Support direct buffers in hpack

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java

Revert to the not-so-good bean handling for the HttpClient executor
Added TODOs so that the bean handling can be updated in future.
Deprecated Websocket client setters that hide dependency on internal HttpClient instance.

Revert backport of HttpClient executor bean handling.

---

jetty-jmx/src/main/java/org/eclipse/jetty/jmx/MBeanContainer.java
jetty-jmx/src/test/java/org/eclipse/jetty/jmx/ObjectMBeanTest.java
jetty-jmx/src/test/java/org/eclipse/jetty/jmx/ObjectMBeanUtilTest.java

Issue #3090.
Corrected places that were making unguarded calls to Class.getPackage().
Added tests for various array cases.

Fixes #3090 - MBeanContainer throws NPE for arrays.

---

pom.xml

Issue #3104 
Released 8.5.33.1 of org.mortbay.apache-jsp to use jetty-schemas-3.1.2 (might take a while before its available on maven central).

Issue #3104 Update to org.mortbay.apache-jsp 8.5.33.1

---

Jenkinsfile

+ Makes things easier to maintain.
+ Does not solve for bad "unstable" flagging of multiple
stages when only one is failing.
See: https://issues.jenkins-ci.org/browse/JENKINS-39203
But this Declarative format will help once that bug is fixed.

Using new Declarative Jenkinsfile format

---

jetty-documentation/src/main/asciidoc/development/frameworks/osgi.adoc
jetty-osgi/test-jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java

Issue #3109 
Remove dependency in jetty-osgi/test-jetty-osgi for aries-util, which is no longer needed; update the documentation; also remove the jetty-schemas-3.1.2 from deployment during the tests, as it is not needed because we use the org.eclipse.jetty.toolchain.jetty-osgi-servlet-api instead (merges the api and the schemas because you can't have split packages in osgi).
@joakime this will probably supercede your PR #3089.

Issue #3109 Remove unnecessary aries-util.

---

jetty-distribution/pom.xml

we must not rely on id.
This was preventing having the logs directory within the distribution.

copying base resources must happen when preparing packaging 

---

jetty-jspc-maven-plugin/src/it/package-root/invoker.properties
jetty-jspc-maven-plugin/src/it/package-root/pom.xml
jetty-jspc-maven-plugin/src/it/package-root/postbuild.groovy
jetty-jspc-maven-plugin/src/it/package-root/src/main/webapp/foo.jsp
jetty-jspc-maven-plugin/src/main/java/org/eclipse/jetty/jspc/plugin/JspcMojo.java

Fixes #3156 . First patch is a general cleanup the other one restores the packageRoot parameter implementation.

Bring back packageRoot parameter in jetty-jspc-maven-plugin

---

jetty-alpn/jetty-alpn-java-server/pom.xml
jetty-annotations/pom.xml
jetty-client/pom.xml
jetty-deploy/pom.xml
jetty-http/pom.xml
jetty-http2/http2-client/pom.xml
jetty-http2/http2-http-client-transport/pom.xml
jetty-http2/http2-server/pom.xml
jetty-jmx/pom.xml
jetty-quickstart/pom.xml
jetty-servlets/pom.xml
jetty-util/pom.xml
jetty-webapp/pom.xml
jetty-websocket/javax-websocket-server/pom.xml
pom.xml

Currently the build is locale dependent. (9.4.x branch is not)
With my locale en_AUS date parsing is failing.

Jetty 10.0.x fix surefire arg line (to avoid locale dependent build)

---

jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java

This interface is currently package-private while it's in the
signature of several public methods (e.g. addLowResourceCheck, getLowResourceChecks)
Signed-off-by: Bjørn Christian Seime <bjorncs@yahoo-inc.com>

Change access of LowResourceCheck to public

---

jetty-maven-plugin/src/it/it-parent-pom/pom.xml
jetty-maven-plugin/src/it/javax-annotation-api/pom.xml
jetty-util/src/main/config/modules/slf4j-api.mod
jetty-util/src/main/config/modules/slf4j-log4j2.mod
pom.xml

upgrade logback and log4j-slf4j (new artifact log4j-slf4j18-impl) to support slf4j api 1.8 

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java

Fix #3207 by providing async compliant print methods

Issue #3207

---

jetty-websocket/websocket-core/fuzzingclient.json
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/compress/CompressExtension.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/compress/DeflateFrameExtension.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/compress/PerMessageDeflateExtension.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/autobahn/AutobahnWebSocketNegotiator.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/DeflateFrameExtensionTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ExtensionTool.java

removed maxFrameSize from `CompressExtension` now use the `WebSocketChannel.getMaxFrameSize()` to fix a bug where a change in the `WebSocketChanel` maxFrameSize was not reaching the `CompressExtension`
create dummy `WebSocketChannel` in all tests which were using a `CompressExtension` without
a channel, as the the extension now uses the channels maxFrameSize
increased the maxFrameSize in `AutobahnWebSocketNegotiator` to fix
autobahn tests being over maxFrameSize after being inflated
#3216

Issue #3216 - Autobahn WebSocketServer failures in jetty 10

---

jetty-webapp/pom.xml
jetty-webapp/src/test/java/org/eclipse/jetty/webapp/MetaInfConfigurationTest.java

See in particular the comment on the MetaInfConfigurationTest.testFindAndFilterContainerPathsJDK9() method for relevant info on differences in classpath/modulepath behaviour of the surefire plugin in jetty-9.4 and jetty-10.0.

Issue #3213 Ensure MetaInfConfigurationTest is not disabled

---

jetty-server/src/test/java/org/eclipse/jetty/server/handler/CustomRequestLogTest.java

Issue #3236 - fixed `CustomRequestLogTest.testLogEnvironmentVar()` failure when `JAVA_HOME` is not set

Issue #3236 - custom request log test failure

---

jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWebAppAsService.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithAnnotations.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJsp.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithWebSocket.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java

#3250 
Put out useful debugging info via a system property on the command line, rather than having to uncomment @Ignore annotations in the osgi tests.

Issue #3250 Ease osgi debugging

---

jetty-jaas/src/main/java/org/eclipse/jetty/jaas/JAASPrincipal.java

It's immutable anyway, so declare its only instance var final. This allows us to directly cache those objects.
Signed-off-by: Ortwin Glück <odi@odi.ch>

make JAASPrincipal thread-safe

---

jetty-osgi/pom.xml

Issue #3274 - Exclude org osgi foundation jar for conflicts with java base classes

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java

#3284 
Fix the situation where the system clock (System.currentTimeMillis) is not consistent. This can lead to the session expiry timer going off *before* the calculated expiry time. The fix is essentially to restart the timer if the expiry time has not been reached when the timer fires. As part of this change, I also changed the way the expiry time is calculated:  before, it was only calculated when the session was accessed; now it is also recalculated when the last request drains out of the session.  This means previously, the time requests spent inside the session actually counted towards the expiry time, which is not quite correct; now, the time at which the session will expire is strictly from the time the session is idle.

Jetty 9.4.x 3284 sessions and system clock jitter

---

jetty-server/src/main/config/etc/jetty-threadpool.xml

#3210
The thread pool is now created as a nested object, rather than a top
level object, so that it is not started before the Server instance.

Fixes #3210 - Threadpool module creates unmanged threadpool.

---

jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/DirectHTTP2OverTLSTest.java
jetty-io/src/test/java/org/eclipse/jetty/io/SslConnectionTest.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ForwardProxyServerTest.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ForwardProxyTLSServerTest.java
jetty-server/src/main/config/etc/jetty-ssl-context.xml
jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/PerMessageDeflateExtensionTest.java
jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/SimpleServletServer.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpChannelAssociationTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportScenario.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/HttpInputIntegrationTest.java

Made default endpointIdentificationAlgorithm=HTTPS to avoid warnings
when SslContextFactory is used on a server.

Issue #3049 - Warn on common SslContextFactory problematic configurations

---

jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java

Issue #3329 
There is a failure when hazelcast expires a session: the HazelcastSessionDataStore.delete(id) calls Hazelcast.remove(key), which will fetch and deserialize the SessionData object being removed. This requires that the calling thread is anointed with the correct classloader (by using ContextHandler.handle(Runnable).  
However, as the SessionData object is never used, we can save on the deserialization and just call Hazelcast.delete(key) instead, which does not fetch the deleted object.

Issue #3329 Hazelcast remove session fails

---

jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java

Issue #3307 
WebAppClassloader.loadClass never uses the resolve parameter that is passed into it. To be correct, we should probably only call Classloader.resolveClass if resolve==true. 
Note that the OP originally reported an NPE, but it turns out that the NPE was caused by a 3rd party (GWT) subclass of WebAppClassLoader that didn't implement the api contract of Classloader.findClass properly (it it returned null instead of ClassNotFoundException if it didn't find a class).  As findClass is never supposed to return null, I'm not in favour of doing a null check before calling resolveClass.

Issue #3307 WebAppClassLoader.loadClass should only call resolveClass if resolve is true

---

jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTLSTest.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslHandshakeListener.java
jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java

Added a SslHandshakeListener to SslConnection that performs
the host name verification (only on the client) if the
HostnameVerifier has been configured in SslContextFactory.

Fixes #3154 - Add support for javax.net.ssl.HostnameVerifier to HttpClient

---

jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
jetty-websocket/javax-websocket-server/src/main/config/modules/websocket.mod

Added --add-modules=ALL-MODULE-PATH by default because now Jetty has
proper JPMS modules and when starting in standalone mode only the
org.eclipse.jetty.xml module will be in the module graph - while
before automatic modules where added to the module graph implicitly.
Added --add-reads=ALL-UNNAMED to the websocket module to allow the
websocket implementation to access method handles of application
classes (the websocket endpoints) that live in the web application
classloader (which forms an unnamed module).

Fixes #3333 - Jetty 10 standalone cannot start on the module-path.

---

jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java
jetty-servlets/src/test/java/org/eclipse/jetty/servlets/CrossOriginFilterTest.java

Currently, the `CrossOriginFilter` will echo the request's "`Origin`" value into the "`Access-Control-Allow-Origin`" response header when it is configured to allow any origin: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java#L401
```
private void handleSimpleResponse(HttpServletRequest request, HttpServletResponse response, String origin)
{
response.setHeader(ACCESS_CONTROL_ALLOW_ORIGIN_HEADER, origin);
//W3C CORS spec http://www.w3.org/TR/cors/#resource-implementation
if (!anyOriginAllowed)
response.addHeader("Vary", ORIGIN_HEADER);
if (allowCredentials)
response.setHeader(ACCESS_CONTROL_ALLOW_CREDENTIALS_HEADER, "true");
if (!exposedHeaders.isEmpty()) …
```

Include Vary:Origin on all responses from CrossOriginFilter

---

jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/Suspender.java
jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/io/SuspenderTest.java

This PR fixes a bug I've run into using Jetty WebSockets in an async I/O pattern, calling `suspend()` upon receiving data from the socket and `resume()` once the data has been handled.  The symptom is that calling `resume()` doesn't actually resume reading from the WebSocket, leading to a hang until socket idle timeout.  While racy, it's fairly reproducible--on my server I can usually trigger it with about a minute of heavy activity.
[eclipse/jetty.project#1219](https://github.com/eclipse/jetty.project/pull/1219) attempted to fix a race condition in the interaction between onFillable() and resume(). But there's a race between the use of these two fields:
```
private final AtomicBoolean suspendToken;
private boolean isFilling;
```
Consider these two fragments in the current code:
``` …
```

Fix race condition between onFillable() and resume()

---

jetty-io/src/main/java/org/eclipse/jetty/io/AbstractEndPoint.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/CloseStatus.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannelState.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketCloseTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketTester.java

#3291 
- introduce channelState check in the catch in WSChannel sendFrame to guard from multiple close notifications in the frameHandler
- removed state change in the isOutputOpen check in webSocketChannelState to as we do the state change in the catch block in WSChannel
- WebSocketConnection fillAndParse will now try to read until EOF and will call the WSChannel to decide what to do when EOF is read, the WSChannel will only treat this as an error if it is not in state ISHUT or CLOSED.
- Fix to the FrameFlusher so that when we call close(Throwable) we set a closeCause throwable which is thrown on the next call to process so that onCompleteFailure is called. This eliminates the race between a process thread and the close thread.
- improvements to WebSocketCloseTest

Issue #3290 - FrameFlusher and WebSocket close fixes

---

jetty-websocket/javax-websocket-server/pom.xml
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/WebSocketServerExamplesTest.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/browser/JsrBrowserConfigurator.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/browser/JsrBrowserDebugTool.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/browser/JsrBrowserSocket.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/examples/GetHttpSessionConfigurator.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/examples/GetHttpSessionSocket.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/examples/MyAuthedConfigurator.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/examples/MyAuthedSocket.java
jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/examples/StreamingEchoSocket.java
jetty-websocket/javax-websocket-server/src/test/resources/jetty-websocket-httpclient.xml

Issue #3165 
Includes changes to the HttpClientProvider done in #3357 as these are waiting to be merged.
- Moved all JsrBrowser classes into package `org.eclipse.jetty.websocket.javax.server.browser`
- Moved Example Classes into package `org.eclipse.jetty.websocket.javax.server.examples`
- Created `WebSocketServerExamplesTest` to run all the examples

Issue #3165 - javax-websocket-server tests

---

jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/PushCacheFilterTest.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/PushedResourcesTest.java
jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushCacheFilter.java
jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushSessionCacheFilter.java

Updated the push filters to use only the Servlet 4.0 APIs,
removing the usage of Jetty specific APIs.

Fixes #3340 - Update PushCacheFilter to use Servlet 4.0 APIs.

---

Jenkinsfile
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTLSTest.java
jetty-home/pom.xml
jetty-infinispan/pom.xml
jetty-util/src/test/java/org/eclipse/jetty/util/LazyListTest.java
pom.xml
tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSessionScavengingTest.java

Add a build with last jdk12 (GA).
This generate 4 test failures:
- org.eclipse.jetty.server.session.ClusteredSessionScavengingTest.testClusteredScavenge
- org.eclipse.jetty.client.HttpClientTLSTest.testClientRawCloseDoesNotInvalidateSession
- org.eclipse.jetty.client.HttpClientTLSTest.testHandshakeSucceededWithSessionResumption
- org.eclipse.jetty.client.HttpClientTLSTest.testMismatchBetweenTLSProtocolAndTLSCiphersOnClient
I guess infinispan is not ready yet for jdk12 so I ignore this one if jdk12.
not sure about the ssl issues....
@sbordet any idea? (ignore if jdk12 as well?)

Add jdk12 build in Jenkinsfile

---

jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
jetty-io/src/main/java/org/eclipse/jetty/io/MappedByteBufferPool.java
jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
jetty-io/src/test/java/org/eclipse/jetty/io/MappedByteBufferPoolTest.java
jetty-server/src/main/config/etc/jetty-bytebufferpool.xml
jetty-server/src/main/config/etc/jetty.xml
jetty-server/src/main/config/modules/bytebufferpool.mod
jetty-server/src/main/config/modules/server.mod

#1861
Implemented a limit for the total memory retained by the
ByteBufferPool for both direct and heap buffers.

Issue #1861 - Limit total bytes pooled by ByteBufferPools.

---

jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/compress/PerMessageDeflateExtension.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ExtensionTool.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/FragmentExtensionTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/PerMessageDeflateExtensionTest.java

For the permessage-deflate extension the `RSV1` bit should be set on only the first frame of a compressed message.
Our current implementation will ignore the `RSV1` bit if it is set on a `CONTINUATION` frame.
We should warn or trigger a `ProtocolException` if the `RSV1` bit is set on any `CONTINUATION` frame.

Issue #3159 - permessage-deflate continuation frame with RSV1 set

---

jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConstants.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/ClientUpgradeRequest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/internal/RFC6455Handshaker.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java

Issue #3412
the autoFragment boolean was never being set on the `Parser` as it was only able to be set on the constructor of `WebSocketConnection` which is called before the point where the channel is customized to set autoFragment

Issue #3412 - WebSocket CoreSession Customizer

---

jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java
jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/FrameHandler.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java

these are the changes from #3365 which are not related to the `WebSocketProxy`
- update javadoc of `FrameHandler`
- pass the cause from the `AbnormalCloseStatus` to closeConnection in
WSChannel
- If `onOpen()` throws we now throw a runtime exception in addition to
failing the callback, this is to fail the `CompletableFuture` in the
`ClientUpgradeRequest`.
- new utility method in `Callback` used in WSChannel and will be used in `WebSocketProxy` as well

WebSocketChannel bug fixes, cleanup and javadoc updates for FrameHandler

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketStatsTest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java

implement connection stats for websockets #3106

Issue #3106 - implement WebSocketConnection stats

---

jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java

Issue #3399
The XmlConfiguration property jetty.webapps.uri should be the uri of the parent of the webapp, but is currently the uri of the webapp itself.  Fixed in jetty-10.0.x to not disturb any users in jetty-9 who are currently relying on the (incorrect) value.

Issue #3399 jetty.webapps.uri should be the parent of the webapp

---

jetty-websocket/jetty-websocket-api/src/main/java/org/eclipse/jetty/websocket/api/extensions/ExtensionConfig.java
jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/JettyUpgradeListener.java
jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java
jetty-websocket/jetty-websocket-common/src/main/java/module-info.java
jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/ExtensionConfigParser.java
jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyExtensionConfig.java
jetty-websocket/jetty-websocket-common/src/main/resources/META-INF/services/org.eclipse.jetty.websocket.api.extensions.ExtensionConfig$Parser
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyServerUpgradeRequest.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyServerUpgradeResponse.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketCreator.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketServerContainer.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/internal/DelegatedJettyServletUpgradeRequest.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseAdapter.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketExtensionConfigTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/extensions/ExtensionConfigTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/util/QuoteUtilTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/util/QuoteUtil_QuoteTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/util/WSURITest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/UpgradeListener.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeResponse.java

#3458 
remove the dependence on jetty-servlet to use websocket server with the jetty-websocket-api
jetty-servlet exposes core classes as it is used by both the javax and jetty sides
a jetty-server `WebSocketCreator` can now be made and be mapped to a pathspec in `JettyWebSocketServerContainer`
jetty-websocket-api now defines interface `ExtensionConfig` which is implemented by `JettyExtensionConfig` in jetty-websocket-common which delegates to the core version, this is to not reimplement this in API and to also not expose the core classes

Issue #3458 - jetty websocket upgrades without using websocket-servlet classes

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/CloseTrackingEndpoint.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/BadNetworkTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java

+ Adding testcase to replicate
+ Fixing CLOSE_WAIT by issuing wsclose + disconnect on eof

Issue #3422 - WebSocket wss CLOSE_WAIT on aborted client connection

---

jetty-websocket/javax-websocket-client/src/main/java/org/eclipse/jetty/websocket/javax/client/JavaxWebSocketClientContainer.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketNegotiationTest.java
jetty-websocket/jetty-websocket-tests/src/test/resources/jetty-logging.properties
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/WebSocketExtensionRegistry.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/ClientUpgradeRequest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/WebSocketCoreClient.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/ExtensionStack.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/compress/PerMessageDeflateExtension.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/Negotiation.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/internal/RFC6455Handshaker.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/GeneratorFrameFlagsTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/GeneratorTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/ParserCapture.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/TestWebSocketNegotiator.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketNegotiationTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketServer.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/DeflateFrameExtensionTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ExtensionStackTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ExtensionTool.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ValidationExtensionTest.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeRequest.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeResponse.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketMapping.java

#3465
- Negotiated now excludes duplicate extension names when setting the negotiated extensions from offered extensions
- do not allow internal extensions to be offered by the client and do not validate internal extensions when set
- Throw exception on websocket errors so the proper status code can be reported back to the client
- WebSocketMapping no longer catches the exceptions and warns but allows them to be caught at a higher level so the appropriate response can be returned
- added tests in core and jetty-websocket to test the negotiation

Issue #3465 - WebSocket Extension Negotiation

---

examples/embedded/src/main/java/org/eclipse/jetty/embedded/WebSocketServer.java
jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/LocalServer.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyServerFrameHandlerFactory.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketConfiguration.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketServlet.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketServletFactory.java
jetty-websocket/jetty-websocket-server/src/test/java/org/eclipse/jetty/websocket/server/browser/BrowserDebugTool.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/EchoCreator.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketServletTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketStatsTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/BadNetworkTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientSessionsTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/SlowClientTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/examples/MyAdvancedEchoCreator.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/examples/MyAdvancedEchoServlet.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/examples/MyAuthedCreator.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/examples/MyAuthedServlet.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/examples/MyEchoServlet.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/ServerCloseCreator.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/ServerCloseTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/SlowServerTest.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java
tests/test-webapps/test-jetty-webapp/pom.xml
tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/WebSocketChatServlet.java

make `WebSocketServlet` part of jetty-websocket-server as it is code specific to the jetty-websocket-api, and should not be exposing core classes to the user
Edit: no longer moving to jetty-websocket-server, now making `WebSocketServlet` generic and extending it in jetty-websocket-server with the class `JettyWebSocketServlet` where the new abstract method `WebSocketServlet.getFactory()` is implemented to get the specific instance of the `JettyServerFrameHandlerFactory`

Issue #3484 - making WebSocketServlet generic

---

jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
jetty-io/src/test/java/org/eclipse/jetty/io/SslConnectionTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java

Fixes #3481 by:
+ if the close notify is not flushed then try again after a thread yield
+ if the retry does not flush then:
- if close is true, don't bother with the flush and just proceed to close the encrypted
- if close is false, schedule an async write to do the flush and proceed as if the decrypted endpoint is closed
Added a test harness with a modified encrypted endpoint to test this behaviour.

Issue #3481 unflushed TLS close notify

---

jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/UpgradeHttpServletRequest.java

#3526.
Trivial fix, the locale was not copied from the HTTP requets to the
WebSocket upgrade request.

Fixes #3526 - Request locale not retained in WebsocketUpgrade request.

---

jetty-websocket/jetty-websocket-api/src/main/java/org/eclipse/jetty/websocket/api/Session.java
jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/SuspendResumeTest.java

#3382
also added extra information to the suspend javadoc to explain that if you call suspend outside of processing a frame, then it will only suspend read events after the next frame has been received.

Issue #3382 - implement Session.suspend() for jetty-10 jetty-websocket-api

---

jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectorHttpClientTransport.java
jetty-unixsocket/src/main/config/etc/jetty-unixsocket-forwarded.xml
jetty-unixsocket/src/main/config/etc/jetty-unixsocket-http.xml
jetty-unixsocket/src/main/config/etc/jetty-unixsocket-http2c.xml
jetty-unixsocket/src/main/config/etc/jetty-unixsocket-proxy-protocol.xml
jetty-unixsocket/src/main/config/etc/jetty-unixsocket-secure.xml
jetty-unixsocket/src/main/config/etc/jetty-unixsocket.xml
jetty-unixsocket/src/main/config/modules/unixsocket.mod
jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketConnector.java
jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketEndPoint.java
jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/client/HttpClientTransportOverUnixSockets.java
jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/JnrTest.java
jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketClient.java
jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketProxyServer.java
jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketServer.java
jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketTest.java
pom.xml
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientLoadTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/RoundRobinConnectionPoolTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/ServerTimeoutsTest.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportProvider.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportScenario.java

Reviewed the implementation.
Got rid of the single channel stored in the HttpClientTransport.
Re-enabled tests on the Unix socket transport.
Updated JNR to 0.22.

Issue #3180 - Review client support for Unix sockets.

---

jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpConversation.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpRedirector.java
jetty-client/src/main/java/org/eclipse/jetty/client/TimeoutCompleteListener.java
jetty-client/src/main/java/org/eclipse/jetty/client/api/Request.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientAuthenticationTest.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientRedirectTest.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java

#3411.
Removed timeout after copying the request in case of redirects
(and authentications), to avoid that the timeout listener is
notified of intermediate exchanges and resets the timeout.

Fixes #3411 - HttpClient does not timeout during multiple redirection.

---

jetty-websocket/jetty-websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketAdapter.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketStatsTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketCloseTest.java

#3494 
Nulling out values in `WebSocketAdapter` causes race conditions when trying to access session and endpoint externally which was causing errors in the tests, if you call `adapter.getSession().close()` the socket could receive a close just before null out the session and then you get a NPE
There was a race condition in `WebSocketChannel.Flusher.onCompleteFailure()`, where `processConnectionError()` should be called before `super.onCompleteFailure()` to ensure that the
correct close reason is processed before the channel is closed.
In `testWriteException` when the output was shutdown there was a race condition between the client detecting the write failure and the server detecting a read failure and sending a failure response.
We now send a message to block the server from reading so …

Issue #3494 - flaky tests in jetty-websocket-tests ClientCloseTest

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
jetty-util/src/main/java/org/eclipse/jetty/util/thread/TryExecutor.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java

This fixes #3550 by ensure that a new thread is always started when:
+ a task is executed, the queue is not empty and there are no idle threads available (this may race, but will only start addition threads)
+ if a thread exits and the queue is not empty

Jetty 9.4.x 3550 queued thread pool stalled

---

jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java

demand has the potential to throw so make sure that the callback in `JettyWebSocketFrameHandler.onFrame()` is either succeeded or failed but not both

demand before succeeding callback in JettyWebSocketFrameHandler

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ConcurrentConnectTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/EventSocket.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java

Issue #3476
stop any `WebSocketSession`s from being added to new connections if they exist as beans on the `WebSocketClient`

Issue #3476 - previous WebSocketSessions being added to new connections

---

jetty-hazelcast/pom.xml

This looks like a simple oversight, but forces the hazelcast test-jar onto users of `jetty-hazelcast`.

Only include hazelcast test-jar in test scope

---

jetty-documentation/src/main/asciidoc/reference/architecture/jetty-classloading.adoc
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionData.java
jetty-util/src/main/java/org/eclipse/jetty/util/ClassVisibilityChecker.java
jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractSessionDataStoreTest.java

#3597 
Fix for session persistence when using deep structures, especially deep structures based off java.util Collection classes like ArrayList etc.  The problem can be seen if the attribute that is stored is an java.util.ArrayList, containing elements that are classes only known to the webapp:  if the server classloader is used to try and deserialize the elements (because that is the  classloader of ArrayList), this will fail, because the classes of the list elements can only be loaded by the webapp classloader.  The solution  is to check if the class of the attribute, eg the ArrayList, can be seen by the weapp classloader, and if so to use that classloader to deserialize.

Issue #3597 Fix session persistence classloading for deep structures

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketNegotiationTest.java
jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/HandshakeRFC6455.java

Issue #3608 
if the client sends an upgrade request without the Sec-WebSocket-Key header, we will give a 400 response instead of the 500 server error currently given

Issue #3608 - give 400 error response for missing Sec-WebSocket-Key

---

jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/SuspendResumeTest.java

new test case demonstrates an issue with websocket suspend when suspending while processing a frame
fixed this by demanding in `session.resume()`

Issue #3382 - improve testing for WS suspend and fix demand on resume

---

jetty-server/src/main/config/etc/jetty-ssl-context.xml
jetty-server/src/main/config/modules/ssl.mod

#3633.
Updated *.xml and *.mod to reflect the right default (null), rather than "HTTPS".

Fixes #3633 - endpointIdentificationAlgorithm enabled by default jetty-ssl-context.xml.

---

jetty-security/src/main/java/org/eclipse/jetty/security/authentication/ConfigurableSpnegoAuthenticator.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/LoginAuthenticator.java

#3627
Spnego authentication can have multiple client/server round trips, during which time the server needs to keep some info about the in-flight authentication process. This info is kept in a http session. Prior to this PR, after the first client/server round trip we would change the session id and mark it as being secure.  Thus, whilst changing the session id is good, it should not happen until the last request of the authentication sequence is processed when the user is actually authenticated.

Issue #3627 Only renew session id when spnego authentication is fully complete

---

jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketAsyncRemote.java
jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketRemoteEndpoint.java
jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/client/WriteTimeoutTest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/FrameHandler.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/WebSocketWriteTimeoutException.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/ClientUpgradeRequest.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/internal/RFC6455Handshaker.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/internal/FrameFlusherTest.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServletFactory.java

addition of websocket write timeouts in websocket-core in order to implement JSR356 `RemoteEndpoint.Async.setSendTimeout()` for issue #3374

Issue #3374 - WebSocket write timeouts

---

aggregates/jetty-all/pom.xml
aggregates/jetty-websocket-all/pom.xml
jetty-osgi/test-jetty-osgi/pom.xml
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java
jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
jetty-websocket/javax-websocket-client/pom.xml
jetty-websocket/javax-websocket-client/src/main/java/module-info.java
jetty-websocket/javax-websocket-common/pom.xml
jetty-websocket/javax-websocket-common/src/main/java/module-info.java
jetty-websocket/javax-websocket-server/pom.xml
jetty-websocket/javax-websocket-server/src/main/java/module-info.java
jetty-websocket/javax-websocket-tests/pom.xml
pom.xml
tests/test-webapps/test-jetty-webapp/pom.xml

#3197.
Introduced jetty-javax-websocket-api artifact with proper
OSGi manifest entries and JPMS Automatic-Module-Name.

Fixes #3197 - Use jetty specific websocket API jar.

---

jetty-websocket/websocket-client/src/test/java/examples/SimpleEchoSocket.java
jetty-websocket/websocket-client/src/test/java/examples/SimpleSecureEchoClient.java

Adding a Secure `wss://` version of the example seen in documentation.
Needed because `wss://echo.websocket.org` has a poor ssllabs score and seems to only use weak cipher suites.

Updating WebSocket Examples seen in documentation

---

jetty-http/src/main/java/org/eclipse/jetty/http/HostPortHttpField.java
jetty-http/src/main/java/org/eclipse/jetty/http/HttpHeader.java
jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSV.java
jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java
jetty-jmh/src/main/java/org/eclipse/jetty/server/jmh/ForwardBenchmark.java
jetty-server/src/main/config/etc/jetty-http-forwarded.xml
jetty-server/src/main/config/modules/http-forwarded.mod
jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/HostPort.java
jetty-util/src/test/java/org/eclipse/jetty/util/HostPortTest.java

#3630
Added support for the X-Forwarded-Port header.
HostPort now handles the case of a stand alone IPv6 address
Reimplemented header scanning using more efficient Trie and MethodHandles

Issue #3630 Forwarded-Port

---

jetty-client/src/main/java/org/eclipse/jetty/client/util/BasicAuthentication.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientProxyTest.java
jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormInputStreamTest.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java
jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/BaseAuthModule.java
jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/ClientCertAuthModule.java
jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/DigestAuthModule.java
jetty-jaspi/src/test/java/org/eclipse/jetty/security/jaspi/JaspiTest.java
jetty-jmh/src/main/java/org/eclipse/jetty/util/jmh/B64CodeBenchmark.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ConnectHandlerTest.java
jetty-security/src/main/java/org/eclipse/jetty/security/SpnegoLoginService.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/BasicAuthenticator.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/ClientCertAuthenticator.java
jetty-security/src/main/java/org/eclipse/jetty/security/authentication/DigestAuthenticator.java
jetty-security/src/test/java/org/eclipse/jetty/security/ConstraintTest.java
jetty-security/src/test/java/org/eclipse/jetty/security/SpecExampleConstraintTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/B64Code.java
jetty-util/src/main/java/org/eclipse/jetty/util/MultiPartInputStreamParser.java
jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
jetty-util/src/test/java/org/eclipse/jetty/util/B64CodeTest.java
jetty-util/src/test/java/org/eclipse/jetty/util/MultiPartInputStreamTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketNegotiationTest.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/AcceptHash.java
jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/AcceptHashTest.java
jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/test/BlockheadClientRequest.java
jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/WebSocketProtocolTest.java

+ Deprecated B64Code
+ All code that isn't B64CodeTest is now using java.util.Base64
+ B64CodeTest is updated to confirm change to java.util.Base64
is possible without change in behavior. Just have to make
sure you use the appropriate Encoder / Decoder for the task
at hand (default vs mime vs url)

Issue #2909 - Replace B64Code with java.util.Base64

---

jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/FrameHandler.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConstants.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannel.java

revert change causing NPE on `ServerContainer.getDefaultMaxSessionIdleTimeout()`
always set the default websocket idle timeout on the endpoint if no other idle timeout configuration is given

fixes to websocket idle timeout

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java

Issue  #3653.
Change ContextHandler.Context.getClassLoader() method to call SecurityManager.checkPermission(permission) instead of calling the default implementation of AccessController.checkPermission(permission)

Issue #3653 Ensure custom SecurityManager.checkPermission is used.

---

jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpConnectionOverHTTP2.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java

#3605.
Now properly resetting HttpReceiverOverHTTP2.ContentNotifier by overriding
reset() and making sure fields are cleared from previous values.
Also, disable channel recycling by default - needs to be benchmarked
whether it's beneficial or not.

Fixes #3605 - IdleTimeout with Jetty HTTP/2 and InputStreamResponseListener

---

jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java

+ Those methods and constructors that had @Deprecation assigned
that urged the use of HttpClient directly are no longer
annotated as deprecated because of legitimate possibility of
a valid LinkageError

Issue #3663 - Remove @Deprecation's from WebSocketClient

---

jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/EventSocket.java
jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/LocalServer.java
jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/server/SessionTrackingTest.java

- using the JavaxWebSocketClientContainer instead of the Fuzzer
- wait for the SessionListener notification to be sure the SessionTracker was notified of the close

Issue #83 - reworked SessionTrackingTest to fix intermittent failures

---

jetty-bom/pom.xml

#3680 
Removed infinispan-remote and infinispan-embedded artifacts from the bom as they are config only. Also added infinispan-common, which was not included transitively before.

Issue #3680 Remove config-only infinispan artifacts from bom.

---

jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterMapping.java
jetty-websocket/jetty-websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeFilter.java

some minor fixes found while testing cometd6

Some fixes for running cometd6 on jetty-10

---

jetty-maven-plugin/README_INTEGRATION_TEST.md
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/common/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/common/src/main/java/mca/common/CommonService.java
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/invoker.properties
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/module/module-api/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/module/module-api/src/main/java/mca/module/ModuleApi.java
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/module/module-impl/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/module/module-impl/src/main/java/mca/module/ModuleImpl.java
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/module/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/postbuild.groovy
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/webapp-war/pom.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/webapp-war/src/config/jetty.xml
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/webapp-war/src/main/java/mca/webapp/WebAppServletListener.java
jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/webapp-war/src/main/webapp/WEB-INF/web.xml
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/utils/MavenProjectHelper.java

Greetings,
PR fixes incorrect dependency resolution in goal jetty:run. 
Scope of this PR is restricted to fixing dependencies for "single war".  (moduleA or moduleB case)
```
Module A
org.mca.jetty.moduleA.ModuleA_api -> /C:/jettyProject/module-a/module-a-api/target/classes/org/mca/jetty/moduleA/ModuleA_api.class
org.mca.jetty.moduleA.ModuleA_impl -> /C:/jettyProject/module-a/module-a-impl/target/classes/org/mca/jetty/moduleA/ModuleA_impl.class
org.mca.jetty.moduleA.ModuleA_servlet -> /C:/jettyProject/module-a/module-a-war/target/classes/org/mca/jetty/moduleA/ModuleA_servlet.class
```
Scanner is triggering hot reload correctly now.
Logic around overlays is still broken (still depends on "unpack" functionality) and will be fixed in future PR.
For more info review #3332.
Cheers,
-- mb

Fixes #3332 jetty-maven-plugin - transitive deps in single war project

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestHttpSessionListenerWithWebappClasses.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SessionListenerTest.java

#3722 
Ensure HttpSessionListener.sessionDestroyed thread caller annointed with webapp classloader. Note that the sessionCreated method never needs the same treatment as it is always called from a request thread.

Jetty 9.4.x 3722 session destroy listeners

---

jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/CloseStatus.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/internal/FrameFlusherTest.java

#3666 
if the `FrameFlusher` receives a CloseFrame with an error status it will not queue these frames behind the frames already queued in the `FrameFlusher`, but will fail all frames waiting to be sent and send the error CloseFrame instead

Issue #3666 - error CloseFrames skip frames in the FrameFlusher queue

---

jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
jetty-xml/src/test/java/org/eclipse/jetty/xml/AnnotatedTestConfiguration.java
jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java

#3713.
Added warnings for invocation of deprecated constructors and methods.
Moved methods exclusively used by XmlConfiguration from TypeUtil.

#3713 - Emit warning when invoking deprecated method in Jetty XML.

---

jetty-websocket/jetty-websocket-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/WebSocket.java
jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientConfigTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/ServerConfigTest.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java
jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketUpgradeFilter.java

Issue #3712 
- renamed maxIdleTime usage to idleTimeout, `Session.setMaxIdleTimeout` remains but this is part of the javax api
- also changed default values of the `@WebSocket` annotation to -1 from -2, this should not change any behavior

Issue #3712 - rename maxIdleTime usage to idleTimeout for WebSockets

---

jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartParser.java
jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormInputStreamTest.java
jetty-server/src/main/java/org/eclipse/jetty/server/MultiParts.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-servlet/pom.xml
jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/MultiPartServletTest.java

Issue #3683
- separated the parsing from the constructor of `MultiParts` so the `Request.__MULTIPARTS` attribute can be set before a parsing error occurs
- added test to replicate the issue where the files are not deleted when an error occurs
- general cleanups of `MultiParts` and `MultiPartFormInputStream`

Issue #3683 - ensure multipart files are still cleaned up if error occurs

---

jetty-util/pom.xml

#3726 
Make osgi Export-Package explicit for org.eclipse.jetty.util to avoid including the transitive dependency on javax.servlet introduced by MultiPartInputStreamParser, which is a deprecated class and is removed in jetty-10.

Remove jetty-util transitive OSGi dependency on servlet-api #3726

---

jetty-jndi/src/main/java/org/eclipse/jetty/jndi/ContextFactory.java
jetty-jndi/src/main/java/org/eclipse/jetty/jndi/InitialContextFactory.java
jetty-jndi/src/main/java/org/eclipse/jetty/jndi/NamingContext.java
jetty-jndi/src/main/java/org/eclipse/jetty/jndi/local/localContextRoot.java
jetty-jndi/src/test/java/org/eclipse/jetty/jndi/java/TestJNDI.java
jetty-plus/src/main/java/org/eclipse/jetty/plus/webapp/PlusConfiguration.java

#3729 
The creation of the java:comp/env namespace is not threadsafe. According to the jndi spec, access to naming Contexts is not threadsafe, and callers must do any synchronization themselves. So we should ensure that we create the java:comp/env namespace in a threadsafe manner. Also:
-  went above-and-beyond and ensured thread safety for adding/removing bindings and subcontexts to Contexts
- ensured that the java:comp context is made readonly all the way down the subcontext tree once the webapp starts
- some tweaks to the Context locking mechanism (which is the implementation of read-only) 
-  did a general code-cleanup of cruft

Jetty 9.4.x 3729 concurrent naming context

---

jetty-jmh/src/main/java/org/eclipse/jetty/util/log/LogCondensePackageStringBenchmark.java
jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
jetty-util/src/main/java/org/eclipse/jetty/util/log/AbstractLogger.java
jetty-util/src/test/java/org/eclipse/jetty/util/log/LogTest.java

#3715
+ Adding alternate implementation
+ Adding more unit tests
+ Fixing original implementation
+ Removing Logger from StringUtil
+ Adding jmh test to compare implementations

Issue #3715 - Improve Log condensePackageString() performance

---

jetty-jndi/src/main/java/org/eclipse/jetty/jndi/NamingContext.java
jetty-jndi/src/test/java/org/eclipse/jetty/jndi/java/TestJNDI.java
tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DemoBaseTests.java
tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/AnnotatedAsyncListenerTest.java

#3748 
Remove deep locking of java:comp/env that was added by #3729. This prevents the @Resource injection of AsyncListeners, possibly other servlet artifacts that are lazily created.
Deep locking needs to be re-evaluated.

Issue #3748 Fix regression for injecting Resource on AsyncListeners

---

jetty-websocket/javax-websocket-server/src/test/java/org/eclipse/jetty/websocket/javax/server/WebSocketServerExamplesTest.java
jetty-websocket/javax-websocket-server/src/test/resources/jetty-websocket-httpclient.xml
jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/CoreServer.java
jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/LocalServer.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketExtensionConfigTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketFilterTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketNegotiationTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/JettyWebSocketServletTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketServletExamplesTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketStatsTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/BadNetworkTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientSessionsTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/SlowClientTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/ServerCloseTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/SlowServerTest.java
jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/WebSocketServer.java

Issue #3762 - use the default port of 0 for WebSocket tests

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpSender.java
jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpSenderOverHTTP.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpSenderOverFCGI.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/TrailersTest.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpSenderOverHTTP2.java
jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/RequestTrailersTest.java

Modified the sender logic to allow specific subclasses to decide
when to send the trailers, if any.
This allows HTTP/2 to correctly compute the end_stream flag and avoid
sending empty trailers frames with end_stream=true.

Issue #3758 - Avoid sending empty trailer frames for http/2 requests.

---

jetty-gcloud/jetty-gcloud-session-manager/pom.xml
jetty-server/src/main/config/etc/jetty-http-forwarded.xml
jetty-server/src/main/config/modules/http-forwarded.mod
jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
jetty-server/src/test/resources/jetty-logging.properties

+ Making existing testcases more reliable and easier to maintain.
+ Updating testcases to test requestURL as well.
+ Adding new testcases for `X-Forwarded-Port` where they only modify the port of an existing `Host:` header.

Issue #3782 - X-Forwarded-Port refers to node listening port

---

jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java

#3785
fix QueuedThreadPoolTest by making sure the jobs are actually run before calling QTP.stop()

Issue #3785 - fix failures in QTP testLifeCycleStop

---

jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/PropertyFileLoginModule.java
jetty-jaas/src/test/java/org/eclipse/jetty/jaas/spi/PropertyFileLoginModuleTest.java
jetty-jaas/src/test/resources/login.properties

#3815
The UserPrincipal for the user was being added as a role name. Eg given  a login.properties file containing:
```
fred=pwd,role1,role2
```
Then the roles would list as:  fred,role1,role2.  After the fix, the roles are: role1,role2.

Issue #3815 Ensure user not in roles for PropertyFileLoginModule

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WriteAfterStopTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/CompressExtension.java

fail the current entry if a failure occurs in the `CompressExtension.Flusher`
this should fix #2061 'WebSocket hangs in blockingWrite', which is replicated in WriteAfterStopTest

Issue #2061 - fail current entry in CompressExtension on failure

---

jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java

This is a minimal fix for #3806 the async race of sendError using isHandled 
at the same time as the normal dispatch is exiting.
This fix is just for a quick release while a more complete solution (with better testing) is developed (see #3850)

Issue #3806 async sendError (minimal fix)

---

jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/ResponseTrailerTest.java
jetty-http2/http2-http-client-transport/src/test/resources/jetty-logging.properties
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java

#3829.
Fixed the logic to send response trailers.

Fixes #3829 - Avoid sending empty trailer frames for http/2 responses.

---

jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java

#3822.
Made TRUST_ALL_CERTS implement X509ExtendedTrustManager,
so that it does not get wrapped in sun.security.ssl.AbstractTrustManagerWrapper,
which performs additional trust checks.

Fixes #3822 - trustAll will not work on some servers.

---

jetty-http/src/main/java/org/eclipse/jetty/http/ResourceHttpContent.java
jetty-server/src/main/java/org/eclipse/jetty/server/CachedContentFactory.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/ResourceCacheTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
jetty-webapp/pom.xml
jetty-webapp/src/test/java/org/eclipse/jetty/webapp/HugeResourceTest.java

Issue #3888 - Huge file Resources behaviors

---

jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
jetty-server/src/main/java/org/eclipse/jetty/server/resource/ByteBufferRangeWriter.java
jetty-server/src/main/java/org/eclipse/jetty/server/resource/HttpContentRangeWriter.java
jetty-server/src/main/java/org/eclipse/jetty/server/resource/InputStreamRangeWriter.java
jetty-server/src/main/java/org/eclipse/jetty/server/resource/RangeWriter.java
jetty-server/src/main/java/org/eclipse/jetty/server/resource/SeekableByteChannelRangeWriter.java
jetty-server/src/test/java/org/eclipse/jetty/server/resource/RangeWriterTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
jetty-util/src/test/java/org/eclipse/jetty/util/resource/PathResourceTest.java

+ Reverting toFile().getInputStream() on PathResource
+ Adding RangeWriter concept for managing open resource across multiple range writes
+ RangeWriter implementation delegates to HttpContent behaviors (will use Cached version, or not, depending on prior ContentFactory behavior)
Lookup is :
- Direct Buffer
- Indirect Buffer
- ReadableByteChannel (as SeekableByteChannel)
- InputStream
+ Adding unit tests for all RangeWriter implementation to ensure that they behave the same way everywhere.
+ Making ResourceService use new RangeWriter implementation
+ Existing DefaultServletRangeTest still works as-is

Issue #3840 Static resource byte-range support performance

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/CloseTrackingEndpoint.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/EchoSocket.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/WebSocketClientTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/FrameAnnotationTest.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/FrameListenerTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyListenerEventDriver.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/NullMessage.java

Issue #3884 - Pure WebSocketFrameListener should not process Continuation events

---

jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java
jetty-util/src/test/java/org/eclipse/jetty/util/component/ContainerLifeCycleTest.java

#3929.
Previously beans were started if they were not running, which
included them being in a STOPPING state.
Now beans are only started if they are in STOPPED state.

Fixes #3929 - Deadlock between new HTTP2Connection() and Server.stop().

---

jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/AsyncServletTest.java
jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/StreamResetTest.java
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java
jetty-io/src/main/java/org/eclipse/jetty/io/AbstractEndPoint.java
jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java
tests/test-http-client-transport/src/test/resources/jetty-logging.properties

#3601.
The client reset wakes up threads blocked in
writes, but these may again attempt to write,
therefore blocking again.
Now we detect that the stream is not writable
and mark the transport as failed, so that
writes fail immediately without blocking.

Fixes #3601 - HTTP2 stall on reset streams.

---

jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/FormTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java

#3856.
Fixed zero checks and exception messages.

Fixes #3856 - Different behaviour with maxFormContentSize=0 if Content-Length header is present/missing.

---

build-resources/src/main/resources/jetty-checkstyle.xml

Removing `AbbreviationAsWordInName` module

---

pom.xml
scripts/release-jetty.sh

avoid too many duplicate artifacts.

Jetty 9.4.x release faster (no need of triggering plugins already triggered)

---

jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java

+ Fixing ForwardedRequestCustomizer.getForwardedPortHeader()
+ Fixing ForwardedRequestCustomizer.setForwardedPortHeader(String)
+ Refactoring unit tests:
+ Tests default ForwardedRequestCustomizer behavior
on one Connector
+ Tests header configured ForwardedRequestCustomizer behavior
on different Connector

Fixes #3969 - Fixing X-Forwarded-Port header setter

---

jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/ReadState.java
jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/io/ReadStateTest.java

Issue #3968
If someone called `AbstractWebSocketConnection.resume()` in between the calls `readState.suspendParse(buffer)` and `readState.suspend()` it could result in `fillInterested()` being called twice.
These changes combine `ReadMode` and `ReadState` so decisions can be made atomically.

Issue #3968 - prevent ReadPending and ISE from AbstractWebSocketConnection

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionCache.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
tests/test-sessions/test-jdbc-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSessionMigrationTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredSessionScavengingTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractWebAppObjectInSessionTest.java
tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestContextScopeListener.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AsyncTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/CreationTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DefaultSessionCacheTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DirtyAttributeTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/IdleSessionTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/NullSessionCacheTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SaveOptimizeTest.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SessionRenewTest.java

#3913
Fixed races in the reference counting used by sessioncache to work out when it can evict a session. As part of fixing races, also discovered a couple of other problem cases to do with complex server-side forwarding chains to other contexts, and also problems with cleaning up sessions on async dispatches. The code is now a lot simpler and clearer in the lifecycle and reference counts for sessions.

Issue #3913 Fix races in session request reference counting

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/session/SessionHandlerTest.java

according to Javadoc and failing tck tests
ServletContext#setSessionTrackingModes
IllegalArgumentException - if sessionTrackingModes specifies a combination of SessionTrackingMode.SSL with a session tracking mode other than SessionTrackingMode.SSL
https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html#setSessionTrackingModes-java.util.Set-

ServletContext#setSessionTrackingModes throw IAE if SSL and another mode

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
jetty-server/src/main/java/org/eclipse/jetty/server/Response.java

There's a change coming up that changes SameSite behaviors in Chrome so there may be more demand to specify this field.
I matched this change to the suggestion in the ticket on a per-cookie basis. Setting this as a global flag would be another approach but this is less invasive of a change.
The three possible specified values are "None", "Lax", and "Strict". The "Excluded" enum value, in this case, causes the field to not be sent (which matches current behavior).

Issue #3040 - Allow RFC6265 Cookies to include optional SameSite attribute

---

jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java

+ Adds onSelectFailed(Throwable)
+ Adds startSelector()
+ Unit test to demonstrate behavior on both execution
strategies

Fixes #3989 - Selector restart with custom ManagedSelector

---

pom.xml

* Tycho to 1.4.0
* CBI to 1.1.7
These updates are important for both speed and m2e compatibility so
warnings are not shown in the eclipse ide.
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

Update Tycho and Eclipse CBI plugins.

---

jetty-server/src/main/java/org/eclipse/jetty/server/CookieCutter.java
jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutterTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutter_LenientTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java

#3985
* If a cookie has no value it is rejected and not stored.
- `name` is rejected
- `name=` is accepted, with empty value

Fixes #3985 - Updates to CookieCutter to reject no-equal cookies

---

jetty-server/src/main/java/org/eclipse/jetty/server/SameFileAliasChecker.java
jetty-server/src/main/java/org/eclipse/jetty/server/handler/AllowSymLinkAliasChecker.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DefaultServletTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java

#4000 
+ OSX File is `swedish-å.txt`
+ OSX File System stores filename in alt UTF-8 (NFD) form. `swedish-a%CC%8A.txt`
+ HTTP uses normal form UTF-8. `swedish-%C3%A5.txt`
+ A HTTP GET request should work against the resource
being requested, regardless of UTF-8 style used.

Issue #4000 - new SameFileAliasChecker to help with NFC/NFD UTF-8 differences

---

jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionData.java

SessionData#setAttribute has a side effect to returned instance of SessionData#getKeys.
Therefore SessionData#setAttribute is called in for ... of loop,
for ... of iteration would throw ConcurrentModificationException.
for fix this problem, It is good to use new HashSet for for ... of loop
Stacktrace:
```
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
at org.eclipse.jetty.server.session.Session.finishInvalidate(Session.java:1093)
at org.eclipse.jetty.server.session.Session.invalidate(Session.java:979)
```

fix Session#finishInvalidate throwsConcurrentModificationException

---

jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java

Hi,
Accept-Encoding seems to be one of those headers that can occur multiple times in a request. GzipHandler doesn't tolerate this at the moment and causes issues like spring-projects/spring-boot#18176.
This PR is an attempt to fix this.
Cheers,
Christoph

Tolerate multiple Accept-Encoding headers in GzipHandler

---

jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java

#4076 
Ensure ServletContainerInitializerStarter added by QuickStartConfigurion.configure() method is removed in QuickStartConfiguration.postConfigure() method.

Issue #4076 Fix restart of quickstarted webapp

---

jetty-server/src/main/config/modules/jdbc.mod
jetty-server/src/main/config/modules/session-store-jdbc.mod
jetty-server/src/main/config/modules/sessions/jdbc/datasource.mod
jetty-server/src/main/config/modules/sessions/jdbc/driver.mod
tests/test-webapps/test-jetty-webapp/src/main/config/demo-base/start.d/demo.ini

Introduced module `jdbc` and made other modules that require JDBC depend on it.
Modified demo.ini to enable the `jdbc` module because some webapp descriptor
of the demo requires JDBC classes.
Now the demo can be run fine on the module-path just by adding --jpms.

Fixes #3747 - Make Jetty Demo work with JPMS.

---

jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
jetty-xml/src/test/java/org/eclipse/jetty/xml/AnnotatedTestConfiguration.java
jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java

+ The XML warning on Deprecated will be squelched (set to DEBUG)
if the `<Set>` call has a `<Property>` (or `<SystemProperty>`)
that is using its default value, and the value resolved from
all items below the `<Set>` is the same value.
All other uses will still result in normal WARN level logging event.

Issue #4084 - squelch deprecated warning on <Set> call.

---

jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpConnectionOverHTTP.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java

1. Now forwarding the fillable event rather than assuming that is due
to garbage bytes or by a server close. This ensures that a HTTP read
consumes the TLS bytes and the `NewSessionTicket` message.
2. Avoid to set the `SslConnection` onto the `EndPoint` in
`SslClientConnectionFactory` - this allows upgrades to work properly,
for example when tunnelling through a secure proxy.

Fixes #4113 - HttpClient fails with JDK 13 and TLS 1.3.

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/SuspendResumeTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/ReadState.java
jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/io/ReadStateTest.java

Issue #3734
Changes from #4095 for jetty-9.4.x.
Make suspending or resuming after close result in ISE.

Issue #3734 - throw ISE for WebSocket suspend after close (jetty-9.4)

---

examples/embedded/src/test/java/org/eclipse/jetty/embedded/ProxyServerTest.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpSender.java
jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpSenderOverHTTP.java
jetty-client/src/test/java/org/eclipse/jetty/client/HostnameVerificationTest.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
jetty-io/src/test/resources/jetty-logging.properties

@gregw the real fix is in commit 2c75e87.
I gave up trying to solve the "race" because calling `completeWrite()` directly may succeed the callback that calls application (or test) code that may block (especially in the client).
We have tests that do that: block the write side until the read side completes. If we don't dispatch `completeWrite()` we don't execute the next line of code that would wake up the read side, so we deadlock.
Instead, exceptions happening in `fill()` or `flush()` are now remembered in a field, and rethrown if further `fill()` operations are triggered.
If a second exception is thrown, the first one is rethrown, with the second as suppressed.
This ensures that the original exception is always reported, no matter if it was generated on the write side but we are now on …

Issue #3787 - Jetty client throws EOFException instead of SSLHandshakeException on certificate errors

---

jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java

This fixes an NPE reported in issue #4130 . It can be triggered by adding the OpenID module and changing the `openid.ini` module created by that to not have any scopes, like this:
```
#jetty.openid.scopes=
```
This PR fixes the NPE.

Issue #4130 - Don't add scopes if none are provided

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java

In issue #4096 a thread was getting stuck in the `ReservedThreadExecutor.ReservedThread.reservedWait()` when stopping the thread pool.
This change allows the thread to exit the loop if the `ReservedThreadExecutor` is no longer running.

Issue #4096 - allow thread to exit ReservedThreadExecutor on stop

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/EventSocket.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WriteAfterStopTest.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java
jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/io/WebSocketClientConnection.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerConnection.java

Issue #4104
Outgoing frames will now go `RemoteEndpoint->Session->ExtensionStack`
instead of just `RemoteEndpoint->ExtensionStack.`
This will allow the Session to check whether it has been closed before
allowing the frame through the ExtensionStack.

Issue #4104 - WebSocketSession will reject outgoing frames if closed

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java

This pull request fixes an issue that causes JMX ObjectNames for Destinations to be non-determistic.
This is due to a race condition in the original code of HttpClient : since computeIfAbsent was not used, the usual pattern (create - putIfAbsent - keep the version that is really in the map) is used.
The issue is that registering the JMX Bean is done at creation time, and not at the end of the process, which makes it possible to register a bean for the same destination more than once, making it impossible to have a deterministic name for the JMX probe. (It also forces to unregister a destination if it needs to be discarded)
Side note : this issue was revealed when trying to use a naming strategy for destinations that allows a consistent collection of metrics (clientName_scheme_host_port). …

support meaningful JMX ObjectNames for HttpDestinations by avoiding race condition at creation

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java

A combined PR for several QTP fixes:
- #4105 Threads without jobs now check if they should idle die before waiting rather than before, this allows idling under steady load. 3ad6780
- #4121 ThreadFactory behaviour supported by doing thread config within `newThread` call. 7b306d7
- #4122 Always clear the interrupted status. c37a4ff

Jetty 9.4.x 4105 4121 4122 queued thread pool

---

jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
jetty-util/src/test/java/org/eclipse/jetty/util/thread/ThreadFactoryTest.java

Issue #4121 - ThreadFactory support in QTP

---

README.md

This causes test artifacts to be built even though tests are not run.
Signed-off-by: Jesse Wilson <jwilson@squareup.com>

Better advice for skipping tests in README.md

---

jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java

This fixes the issue (#4128) I raised about incorrect decoding of some ID token JWTs that have sections that need their padding added back.

Issue #4128 - Add missing padding and use URL decoder

---

jetty-openid/src/main/config/etc/jetty-openid.xml
jetty-openid/src/main/config/modules/openid.mod
jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java
jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java
jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdLoginService.java

This PR makes the token and authorization endpoints of the OpenID Connect Provider (OP) configuration, so that metadata doesn't have to be fetched (for whatever reason). See issue #4132 for more details.

Issue #4132 - Allow token and authorization endpoints to be configured

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
jetty-client/src/main/java/org/eclipse/jetty/client/ResponseNotifier.java
jetty-client/src/main/java/org/eclipse/jetty/client/api/Request.java
jetty-client/src/main/java/org/eclipse/jetty/client/api/Response.java
jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientGZIPTest.java
jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpChannelOverFCGI.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpConnectionOverFCGI.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpReceiverOverFCGI.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java
jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ForwardProxyTLSServerTest.java
jetty-util/src/main/java/org/eclipse/jetty/util/CompletableCallback.java
jetty-util/src/main/java/org/eclipse/jetty/util/MathUtils.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientDemandTest.java
tests/test-http-client-transport/src/test/resources/jetty-logging.properties

Introduced a Response.DemandedContentListener to explicitly separate
the will to request more content from the notification that the content
has been consumed.
Updated all transports to follow the new semantic: rather than waiting
for the callback to complete before delivering more content, now they
wait for the demand to be positive to deliver more content.
Since now the content may be unconsumed but there can be more demand,
all transport implementation had to be changed to use RetainableByteBuffer
to retain content buffers that were not consumed.

Issue #2429 - Review HttpClient backpressure semantic.

---

jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java

There is a race between the doStop clearing the key map and the watching thread
checking isRunning before iterating over the key map.
While more sophisticated approaches could be used, I think that is best to defer
until this class is reworked entirely.  For now just using a ConcurrentHashMap will
avoid the exception and the closing of the pathwatcher will prevent watching forever.

Pathwatcher Concurrent modification #4174

---

jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ConcurrentConnectTest.java
jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java

Issue #3558 - only notify WS onError if onClose has not been called

---

jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java

SendError now makes the response immutable for headers and status. #4176

Issue #4176 setHeader after sendError

---

jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/RequestDispatchedSessionTest.java

Fix for #4156 :
+ check validity of sessions in getSession(SessionHandler)
+ do not replace session in doScope if SessionHandler is the same.

Issue #4156 - Session Already in Cache during forwarding

---

jetty-util/src/test/java/org/eclipse/jetty/util/MultiMapTest.java

In this PR, we propose to fix #4195 by making the test assertions consider both valid cases of `toString` function of the MultiMap.

Fixes #4195: making test assertion more stable.

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
jetty-server/src/test/java/org/eclipse/jetty/server/HttpManyWaysToCommitTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java

#4208 
Allow Content-Length header in 304 responses
check Content-Length header is allowed in HEAD responses

Issue #4208 - Content-Length in 304

---

jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientConnectTest.java

Issue #4214 - fix flaky ClientConnectTest and change WS connectTimeout

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java
tests/test-integration/src/test/java/org/eclipse/jetty/test/rfcs/RFC2616BaseTest.java

For:
* Issue #4203 - Some `Transfer-Encoding` and `Content-Length` combinations do not result in expected 400 Bad Request
* Issue #4204 - `Transfer-Encoding` behavior does not follow RFC7230

Fixes #4203 and #4204 - Transfer-Encoding + Content-Length behaviors

---

jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTLSTest.java
jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java

#4217
Releasing the encrypted output buffer so that it can be re-acquired
with an expanded capacity.

Fixes #4217 - SslConnection.DecryptedEnpoint.flush eternal busy loop.

---

jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java

Issue #4227 - do not use encodeRedirectURL for openid redirects

---

jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CGI.java
tests/test-webapps/test-jetty-webapp/src/main/webapp/WEB-INF/web.xml

Issue #4240 - use default charset utf-8 for cgi request form encoding

---

jetty-jaspi/pom.xml
jetty-jaspi/src/main/resources/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory
jetty-openid/pom.xml
jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticatorFactory.java
jetty-openid/src/main/resources/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory
jetty-security/pom.xml
jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java
jetty-security/src/main/resources/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory

Issue #4237
Remove the need to use a context xml file to configure the `OpenIdAuthenticatorFactory` and set init param on security handler.
`Authenticator.Factory` is now discovered by the `ServiceLoader`, a list of them is kept in `SecurityHandler` and they are tried one at a time until one creates an `Authenticator`. So it is no longer necessary to set any configuration for the `OpenIdAuthenticatorFactory`.
The init param to configure the openid error page is now to be set in web.xml:
```xml
<context-param>
<param-name>org.eclipse.jetty.security.openid.error_page</param-name>
<param-value>/error</param-value>
</context-param>
```

Issue #4237 - allow openid module to be configured without context xml

---

jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/WebSocketCoreClient.java

adaptation of changes from PR #1777 for jetty-10
Gives an option for the jetty `WebSocketClient` to be automatically stopped at shutdown.
This PR differs from the changes of #1777 in two ways;  it is disabled by default, and we still register it for shutdown if the client has not been started so this will work:
```java
WebSocketClient client = new WebSocketClient();
client.setStopAtShutdown(true);
client.start();
```

configuration for jetty-10 WebSocketClient to be stopped at shutdown

---

jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java

#4282
Fixed handling of returning true from headerComplete() and
contentComplete().

Issue #4282 - Review HttpParser handling in case of no content.

---

jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/RateControl.java
jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/WindowRateControl.java
jetty-http2/http2-server/src/main/config/etc/jetty-http2.xml
jetty-http2/http2-server/src/main/config/etc/jetty-http2c.xml
jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java
tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java

Introduced RateControl.Factory to create instances of RateControl
for each connection.
Modified relevant XML files and added distribution test for h2.
#4258

Fixes #4258 - RateControl should be per-connection.

---

jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpConnectionOverFCGI.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ClientParser.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/Parser.java
jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java
jetty-fcgi/fcgi-client/src/test/java/org/eclipse/jetty/fcgi/generator/ClientGeneratorTest.java
jetty-fcgi/fcgi-client/src/test/java/org/eclipse/jetty/fcgi/parser/ClientParserTest.java
jetty-fcgi/fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/ServerFCGIConnection.java
jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpReceiverOverHTTP2.java
tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientDemandTest.java

Now correctly handling no demand before the content
in FCGI and HTTP2 transports.
Fixed HttpRequest to correctly forward onBeforeContent()
to wrapped listeners.

Fixes #4301 - Demand beforeContent is not forwarded.

---

jetty-jspc-maven-plugin/pom.xml
jetty-jspc-maven-plugin/src/site/markdown/index.md
jetty-jspc-maven-plugin/src/site/site.xml
jetty-maven-plugin/pom.xml
jetty-maven-plugin/src/site/markdown/index.md
jetty-maven-plugin/src/site/site.xml
pom.xml

@jmcc0nn3ll @WalkerWatch  it's really WIP (I'm not really a UI person :) ) and similar change probably need to go as well to jetty-jspc-maven-plugin
Use `mvn clean package -DskipTets -Psite-jar -pl :jetty-maven-plugin`
jar file is available in jetty-maven-plugin/target/jetty-maven-plugin-9.4.15-SNAPSHOT-site.jar

Issue #3247 Generate jetty-maven-plugin website
