eclipse/jetty.project

- jetty-server/src/main/config/etc/jetty.xml
Signed-off-by: Ido <ido.dovrat@gmail.com>
> Add missing property configuration to jetty.xml

- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
nullpointer exception.
Follow up on https://github.com/eclipse/jetty.project/pull/69
Signed CLA now as well.
> Added nullchecks and test for getters using _metadata to avoid throwing

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
> Fix typo in annotation

- jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
Cherry pick of #303 into 9.3.x branch
> 9.3.x: Fetch user roles after a successful forced binded ldap login.

- jetty-websocket/javax-websocket-server-impl/pom.xml
> Issue #418 - Add osgi capability for endpoint configurator

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java
- jetty-server/src/main/java/org/eclipse/jetty/server/ConnectorStatistics.java
- jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
- jetty-server/src/main/java/org/eclipse/jetty/server/jmx/AbstractConnectorMBean.java
- jetty-util/src/main/java/org/eclipse/jetty/util/statistic/CounterStatistic.java
- jetty-util/src/main/java/org/eclipse/jetty/util/statistic/SampleStatistic.java
- jetty-util/src/test/java/org/eclipse/jetty/util/statistic/CounterStatisticTest.java
First cut at #472 using LongAdder and LongAccumulator for statistics.
> Issue #472 Use LongAdder for statistics

- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/EventSender.java
Next try now with signed commit.
> Fix #495 EventSender might leak service-references or miss them at all

- jetty-documentation/src/main/asciidoc/administration/logging/chapter.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-logging.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-request-logs.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/default-logging-with-stderrlog.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-apache-log4j.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-java-util-logging-native.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-java-util-logging.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-logback-centralized-logging.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-logback-sifting.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-logback.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-slf4j-multiple-loggers.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-coordinates.adoc
Updated Chapter 20 with ventilated prose and fixed numerous spelling/grammar/formatting issues.
> Chapter 20 tweaks

- jetty-distribution/src/main/resources/modules/jolokia.mod
the currently used version of jolokia (1.2.2) is about two years out of date
perhaps it's time to update (:
> update jolokia to 1.3.3

- jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ProxyTunnellingTest.java
Signed-off-by: Dhiraj Bokde <dbokde@redhat.com>
> Added test case for HTTP proxy tunneling authorization failure

- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ErrorPageErrorHandler.java
> Fixes #567 - NPE in ErrorPageErrorHandler debug

- jetty-documentation/src/main/asciidoc/administration/logging/default-logging-with-stderrlog.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/dump-tool.adoc
> Reformatting of dump-tool for #549.

- jetty-documentation/src/main/asciidoc/configuring/deploying/anatomy-of-a-webapp.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/automatic-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/chapter.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/configuring-specific-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-architecture.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-processing-webapps.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/hot-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/overlay-deployer.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/quickstart-webapp.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/setting-deployment-bindings.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/static-content-deployment.adoc
> Updated Chapter 4 with ventilated prose and updated grammar/formatting.

- jetty-documentation/src/main/asciidoc/configuring/deploying/anatomy-of-a-webapp.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-processing-webapps.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/what-to-configure.adoc
- jetty-documentation/src/main/asciidoc/reference/troubleshooting/security-reports.adoc
> Added note for CVE-2016-4800 and several small grammatical clean ups.

- jetty-documentation/src/main/asciidoc/administration/sessions/session-clustering-gcloud-datastore.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-clustering-infinispan.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-clustering-jdbc.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-clustering-mongodb.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/setting-session-characteristics.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/using-persistent-sessions.adoc
> Chapter 10 clean up and link fixes.

- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/MetaInfConfiguration.java
> Issue #628 resolve by checking for existing jar: prefix on uri

- jetty-documentation/src/main/asciidoc/development/embedding/embedded-examples.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/embedding-jetty.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-file-server.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-many-connectors.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-minimal-servlet.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-one-webapp.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-secured-hello-handler.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/examples/embedded-split-file-server.adoc
- jetty-documentation/src/main/asciidoc/development/embedding/jetty-helloworld.adoc
> Chapter 24 touch-ups.

- jetty-server/src/main/config/etc/jetty-requestlog.xml
> Correcting path for #645

- jetty-documentation/src/main/asciidoc/configuring/deploying/configuring-specific-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-processing-webapps.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/chapter.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/how-to-configure.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/what-to-configure.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/chapter.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-deploying.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-installing.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-running.adoc
> Chapter 2 and 3 updates.

- jetty-documentation/src/main/asciidoc/configuring/deploying/automatic-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/configuring-specific-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-architecture.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-processing-webapps.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/hot-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/overlay-deployer.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/static-content-deployment.adoc
> Chapter 4 updates and corrections.

- jetty-documentation/src/main/asciidoc/reference/architecture/jetty-classloading.adoc
> Resolves #701

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-connectors.adoc
- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
- jetty-documentation/src/main/asciidoc/configuring/connectors/setting-port80-access-for-non-root-user.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/quickstart-webapp.adoc
> Chapter 6 fixes, removal of Quickstart pieces for #679.

- jetty-documentation/src/main/asciidoc/configuring/deploying/quickstart-webapp.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/authentication.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/configuring-form-size.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/jaas-support.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/jetty-home-and-jetty-base.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/secure-passwords.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/serving-aliased-files.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/spnego-support.adoc
> Chapter 7 clean up, prose fix.

- jetty-documentation/src/main/asciidoc/administration/startup/chapter.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/screen-empty-base-listconfig.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/screen-empty-base.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/start-jar.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-base-vs-home.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-classpath.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-modules.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-overview.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-xml-config.adoc
- jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/spnego-support.adoc
> Chapter 8 and 9 cleanup.

- jetty-documentation/src/main/asciidoc/administration/startup/startup-unix-service.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-windows-service.adoc
- jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc
> Chapter 9 cleanup and removed doc reference to disablejsr for #706.

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-connectors.adoc
> Fixing SRCDIR references.

- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-request-logs.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-modules.adoc
- jetty-server/src/main/config/etc/jetty-requestlog.xml
- jetty-server/src/main/config/modules/requestlog.mod
> Updated RequestLog xml/module/documentation. Resolves #734

- jetty-documentation/src/main/asciidoc/administration/jndi/chapter.adoc
- jetty-documentation/src/main/asciidoc/administration/jndi/jndi-configuration.adoc
- jetty-documentation/src/main/asciidoc/administration/jndi/jndi-datasources.adoc
- jetty-documentation/src/main/asciidoc/administration/jndi/jndi-embedded.adoc
- jetty-documentation/src/main/asciidoc/administration/jndi/quick-jndi-setup.adoc
- jetty-documentation/src/main/asciidoc/administration/jndi/using-jndi.adoc
> Chapter 12 Updates

- jetty-http/src/main/java/org/eclipse/jetty/http/MimeTypes.java
> Fixes #723 - improves MimeType resource loading and error reporting

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
> Resolves #747.

- jetty-documentation/src/main/asciidoc/administration/alpn/alpn.adoc
- jetty-documentation/src/main/asciidoc/administration/alpn/chapter.adoc
> Chapter 15 cleanup

- jetty-documentation/src/main/asciidoc/administration/http2/configuring-haproxy.adoc
- jetty-documentation/src/main/asciidoc/administration/http2/configuring-http2.adoc
- jetty-documentation/src/main/asciidoc/administration/http2/configuring-push.adoc
- jetty-documentation/src/main/asciidoc/administration/http2/enabling-http2.adoc
- jetty-documentation/src/main/asciidoc/administration/http2/introduction.adoc
> Chapter 16 updates

- jetty-documentation/src/main/asciidoc/administration/http2/configuring-http2.adoc
> Resolves #764.

- jetty-documentation/src/main/asciidoc/administration/extras/balancer-servlet.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/cgi-servlet.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/cross-origin-filter.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/debug-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/default-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/default-servlet.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/dos-filter.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/error-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/gzip-filter.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/ipaccess-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/moved-context-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/proxy-servlet.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/qos-filter.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/rewrite-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/shutdown-handler.adoc
- jetty-documentation/src/main/asciidoc/administration/extras/statistics-handler.adoc
> Updates to Servlets/Filters/Handlers in Chapter 17.

- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-request-logs.adoc
> Resolves #761

- jetty-documentation/src/main/asciidoc/administration/tuning/chapter.adoc
- jetty-documentation/src/main/asciidoc/administration/tuning/garbage-collection.adoc
- jetty-documentation/src/main/asciidoc/administration/tuning/high-load.adoc
- jetty-documentation/src/main/asciidoc/administration/tuning/limit-load.adoc
> Chapter 20 cleanup.

- jetty-documentation/src/main/asciidoc/administration/jmx/jetty-jconsole.adoc
- jetty-documentation/src/main/asciidoc/configuring/contexts/temporary-directories.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-api.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-authentication.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-cookie.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-intro.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-proxy.adoc
- jetty-documentation/src/main/asciidoc/development/clients/http/http-client-transport.adoc
> Chapter 22 revisions and misc adoc updates.

- jetty-documentation/src/main/asciidoc/development/maven/jetty-jspc-maven-plugin.adoc
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-helloworld.adoc
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-scanning.adoc
> Jetty and Maven updates.

- jetty-documentation/src/main/asciidoc/development/handlers/writing-custom-handlers.adoc
> Updates for Jetty Handlers.

- jetty-documentation/src/main/asciidoc/administration/startup/screen-empty-base-listconfig.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/screen-http-webapp-deploy-listconfig.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/screen-http-webapp-deploy.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/screen-list-modules.adoc
> Clean up of Startup examples.

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
> Resolves #860

- jetty-home/src/main/resources/modules/jamon.mod
> Updating jamon version to 2.81 as part of module revisions in #731.

- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-web-xml-config.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-syntax.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-usage.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/override-web-xml.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/webdefault-xml.adoc
> Resolves #872 and cleans up XML chapter.

- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-gcloud.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-infinispan.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-mongodb.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-hierarchy.adoc
> Updates for 9.4 Sessions

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
The right layout of keystore and truststore when enabled two way authentication.
> Two way authentication configuration

- jetty-server/src/main/java/org/eclipse/jetty/server/session/JDBCSessionIdManager.java
> add schema variables

- VERSION.txt
> Removing documentation issues from Version.

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
> Resolves #930

- jetty-documentation/src/main/asciidoc/administration/tuning/high-load.adoc
> Resolves #965

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/FileServer.java
> Resolves #943

- jetty-documentation/src/main/asciidoc/configuring/deploying/quickstart-webapp.adoc
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
> Update quickstart docs for #896

- jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
> Issue #984 - Minor edits to wording.

- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java
> Fix typo in DefaultServlet

- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-logging.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/configuring-logging-modules.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/default-logging-with-stderrlog.adoc
> Issue #644 Documentation updates

- jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
Signed-off-by: SimonDallaway <simon.dallaway@datacom.co.nz>
> fix for userRdnAttribute value != username

- jetty-documentation/src/main/asciidoc/administration/logging/configuring-logging-modules.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/default-logging-with-stderrlog.adoc
- jetty-documentation/src/main/asciidoc/administration/logging/example-logback-centralized-logging.adoc
> Issue #644 Additional documentation for updated logging modules.

- jetty-documentation/src/main/asciidoc/reference/upgrading/upgrading-9.3-to-9.4.adoc
> Updates for upgrading guide.

- jetty-documentation/src/main/asciidoc/development/frameworks/osgi.adoc
> OSGi doc formatting cleanup.

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-connectors.adoc
> Issue #1026 - Added documentation.

- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-gcloud.adoc
> Updates for GCloud sessions.

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/HelloSessionServlet.java
- examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneServletContextWithSession.java
- examples/embedded/src/main/java/org/eclipse/jetty/embedded/StoreInSessionServlet.java
Fix for the #613 issue.
Signed-off-by: Luis Daniel <lalducin@nearsoft.com>
> Added an example of embeded Jetty using hashed session and servlets.

- jetty-documentation/src/main/asciidoc/administration/runner/jetty-runner.adoc
> Issue #1092 Documentation updates.

- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslSelectionDump.java
- jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java
+ Protocol selection details
+ Cipher Suites selection details
> Issue #1108 - adding SslContextFactory.dump() selection details

- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/PostConstructAnnotationHandler.java
- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/PreDestroyAnnotationHandler.java
- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/ResourceAnnotationHandler.java
- jetty-jmx/src/main/java/org/eclipse/jetty/jmx/ObjectMBean.java
- jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSONObjectConvertor.java
- jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSONPojoConvertor.java
- jetty-util/src/main/java/org/eclipse/jetty/util/IntrospectionUtil.java
- jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
> Issue #1135 - Avoid allocations from Method.getParameterTypes() if possible

- jetty-documentation/src/main/asciidoc/configuring/deploying/configuring-specific-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/reference/contributing/patches.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-env-xml.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-web-xml-config.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-config.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-syntax.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-usage.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/override-web-xml.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/webdefault-xml.adoc
> Issue #1138 - Doc updates and cleanup.

- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-memory.adoc
- jetty-documentation/src/main/asciidoc/administration/sessions/session-hierarchy.adoc
- jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc
- jetty-documentation/src/main/asciidoc/reference/upgrading/upgrading-9.3-to-9.4.adoc
> Misc doc updates/fixes.

- jetty-documentation/src/main/asciidoc/configuring/jsp/configuring-jsp.adoc
> Issue #1112 - Doc update.

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
> Issue #1161 - Leaving CookieStore alone HttpClient and WebSocketClient are stopped

- jetty-documentation/src/main/asciidoc/administration/startup/start-jar.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-modules.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/jetty-home-and-jetty-base.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/how-to-configure.adoc
- jetty-start/src/main/resources/org/eclipse/jetty/start/usage.txt
> Issue #1139 - Documented new features and misc cleanup.

- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-installing.adoc
> Resolves #981

- jetty-server/src/main/config/modules/logback-access.mod
> Issue #1188 - Fixed dependency.

- jetty-documentation/src/main/asciidoc/quick-start/introduction/what-version.adoc
Needs pulled up through 9.4.x as well.
> Version updates.

- jetty-documentation/src/main/asciidoc/administration/logging/configuring-jetty-request-logs.adoc
> Update for Log Latency

- Jenkinsfile
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
- jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
- jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
- jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java
- tests/test-integration/src/test/java/org/eclipse/jetty/test/rfcs/RFC2616BaseTest.java
> backport fixes for #592 on 9.2.x branch

- jetty-documentation/src/main/asciidoc/administration/startup/startup-base-vs-home.adoc
- jetty-documentation/src/main/asciidoc/configuring/security/jetty-home-and-jetty-base.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-running.adoc
> Clarfying Jetty Home v Base

- jetty-documentation/src/main/asciidoc/administration/annotations/using-annotations-embedded.adoc
- jetty-documentation/src/main/asciidoc/development/ant/jetty-ant.adoc
- jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-installing.adoc
> Doc fix for download links.

- jetty-documentation/src/main/asciidoc/administration/extras/moved-context-handler.adoc
- jetty-documentation/src/main/asciidoc/configuring/contexts/configuring-virtual-hosts.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/configuring-specific-webapp-deployment.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-architecture.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/deployment-processing-webapps.adoc
- jetty-documentation/src/main/asciidoc/configuring/deploying/static-content-deployment.adoc
- jetty-documentation/src/main/asciidoc/development/frameworks/osgi.adoc
- jetty-documentation/src/main/asciidoc/quick-start/configuring/what-to-configure.adoc
- jetty-documentation/src/main/asciidoc/reference/jetty-xml/jetty-xml-syntax.adoc
> Issue #1230 - Updated dtd reference.

- jetty-documentation/src/main/asciidoc/administration/startup/start-jar.adoc
- jetty-documentation/src/main/asciidoc/administration/startup/startup-base-vs-home.adoc
> Some updates to start doco.

- CONTRIBUTING.md
> Updating contribution instructions for security issues.

- jetty-documentation/src/main/asciidoc/development/embedding/jetty-helloworld.adoc
> Further clarification for jetty-all

- jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java
Signed-off-by: cao tianze <hnrcao@qq.com>
> delete redundant addBean(serverChannel) invoke

- jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
Fix for #1317 that does not cause the deadlock reported in #1363.
> Jetty 9.4.x 1363

- jetty-server/src/main/java/org/eclipse/jetty/server/session/FileSessionDataStore.java
- jetty-server/src/test/java/org/eclipse/jetty/server/session/FileSessionManagerTest.java
Fixes issue #1373.
Signed-off-by: Brandon Mintern <brandon@mintern.net>
> Handle spurious files in sessions directory

- jetty-nosql/pom.xml
- jetty-nosql/src/main/config/modules/session-store-mongo.mod
- jetty-nosql/src/main/java/org/eclipse/jetty/nosql/mongodb/MongoSessionDataStoreFactory.java
Signed-off-by: Jin Zhang <jin.zhang@epicgames.com>
> Issue #856 Add server/port and auth configuration for mongo sessions

- jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/extensions/Frame.java
> Issue #1411 - Use short-circuit operator in websocket Frame

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
- jetty-server/src/test/java/org/eclipse/jetty/server/handler/ContextHandlerTest.java
Initialize the _availability variable properly, as discussed in #1236.
Also, fix a Javadoc comment, add a simple test.
> Fix NPE in ContextHandler.isShutdown

- jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java
> Issue #1334 - throwing a ServletException if unable to commit the response

- jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java
Signed-off-by: John Gardiner Myers <jgmyers@proofpoint.com>
> Allow for easier subclassing of the HttpChannelOverHTTP2.

- jetty-security/src/main/java/org/eclipse/jetty/security/PropertyUserStore.java
> prefer LOG.debug to System.err.println

- jetty-bom/pom.xml
> update bom with new 9.4 modules

- jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutterTest.java
- jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutter_LenientTest.java
> Issue #1546 - more leniency testcase

- jetty-bom/pom.xml
> fix for #1527 9.3.x branch

- jetty-bom/pom.xml
> fix for #1527 9.4.x branch

- jetty-documentation/src/main/asciidoc/administration/sessions/session-configuration-infinispan.adoc
> fix typo in session-configuration-infinispan documentation #1583

- jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpSenderOverHTTP2.java
Change-Id: I2b4f8e8373e3ba16361a37fd1f6549a4a2d97d60
Signed-off-by: Stéphane Martin <stephane.martin@neotys.com>
> HTTP/2 :authority: declaration should omit default ports in jetty-client

- jetty-maven-plugin/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyWebAppContext.java
> run mojo use build.outputDirectory from reactor projects 

- jetty-documentation/src/main/asciidoc/administration/extras/header-filter.adoc
- jetty-servlets/src/main/java/org/eclipse/jetty/servlets/HeaderFilter.java
- jetty-servlets/src/main/java/org/eclipse/jetty/servlets/IncludeExcludeBasedFilter.java
- jetty-servlets/src/test/java/org/eclipse/jetty/servlets/IncludeExcludeBasedFilterTest.java
This also removes the mime type option from HeaderFilter
Signed-off-by: S K (xz64) <xz64.xyz@gmail.com>
We can discuss more on #1622
> Issue #1622 - HeaderFilter does not work if response has been committed

- jetty-maven-plugin/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWithDistro.java
- jetty-maven-plugin/src/main/resources/maven.mod
> use maven-artifact-transfer library

- jetty-maven-plugin/pom.xml
> use invoker plugin 3.0.1 released version

- jetty-documentation/src/main/asciidoc/administration/alpn/alpn.adoc
> Update ALPN documentation for JDK 8u151 and 8u152

- jetty-distribution/pom.xml
- pom.xml
> upgrade assembly plugin and use tarLongFileMode posix #1782 branch 9.3.x

- jetty-distribution/pom.xml
- jetty-home/pom.xml
- pom.xml
> upgrade assembly plugin and use tarLongFileMode posix #1782 branch 9.4.x

- jetty-distribution/pom.xml
- jetty-home/pom.xml
- pom.xml
> Bugfix/tar file mode posix master #1782 (master branch)

- jetty-runner/src/main/java/org/eclipse/jetty/runner/Runner.java
- jetty-server/src/main/java/org/eclipse/jetty/server/ShutdownMonitor.java
support -DSTOP.PORT and -DSTOP.KEY as well #1550
> fix inconsistencies shutdown for JettyRunner 

- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpConnectionOverHTTP.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpSenderOverHTTP.java
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/ConnectionStatisticsTest.java
> implements connection.getBytes[In|Out] for http transport #922

- jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientLoadTest.java
Alternate implementation that is count based rather than time based.
> Issue #1924 - ManagedSelector livelock.

- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/WebAppContextTest.java
#1986 
Signed-off-by: Jan Bartel <janb@webtide.com>
> Issue #1986 ServletContextHandler.Context addListener() methods support session listeners

- jetty-alpn/jetty-alpn-java-client/pom.xml
- jetty-alpn/jetty-alpn-java-server/pom.xml
Adds correct osgi manifest headers for service provided by alpn-java client and server
> Issue #2028 Adding osgi headers for service to alpn-java client and server

- jetty-documentation/src/main/asciidoc/administration/alpn/alpn.adoc
- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
> Fixes #2017 - Documentation on ALPN needs updating.

- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationConfiguration.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/annotations/AnnotationConfiguration.java
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithAnnotations.java
> Issue #2030 fix NPE in AnnotationConfiguration with debug enabled

- jetty-alpn/jetty-alpn-conscrypt-client/pom.xml
- jetty-alpn/jetty-alpn-conscrypt-server/pom.xml
- jetty-alpn/pom.xml
- pom.xml
Adding correct osgi headers to support use of ServiceLoader for the alpn conscrypt client and server.
> Issue #2015 add osgi headers for alpn conscrypt

- jetty-documentation/src/main/asciidoc/administration/http2/configuring-push.adoc
> Fixes #2069 - Update the PushCacheFilter documentation.

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java
EWYK cleanups from #1970
Added PENDING state and removed loops that were no longer used. Simplified debug
> EWYK cleanups from #1970

- jetty-documentation/src/main/asciidoc/development/websockets/jetty/jetty-websocket-api-send-message.adoc
- jetty-documentation/src/main/asciidoc/development/websockets/jetty/jetty-websocket-api-session.adoc
> Fix typo in WebSocket doc.

- jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreFactory.java
- tests/test-sessions/test-hazelcast-sessions/pom.xml
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/ClusteredLastAccessTimeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/ClusteredOrphanedSessionTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/ClusteredSessionMigrationTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/ClusteredSessionScavengingTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/ModifyMaxInactiveIntervalTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/NonClusteredSessionScavengingTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/SessionExpiryTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/SessionInvalidateCreateScavengeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientLastAccessTimeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientModifyMaxInactiveIntervalTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientNonClusteredSessionScavengingTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientOrphanedSessionTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionExpiryTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionInvalidateCreateScavengeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionMigrationTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionScavengingTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/resources/jetty-logging.properties
- tests/test-sessions/test-hazelcast-sessions/src/test/resources/logging.properties
after reviewing some code ensure we really only use client mode in all tests.
> ensure we really use only client test

- jetty-unixsocket/pom.xml
- jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketConnector.java
- jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/client/HttpClientTransportOverUnixSockets.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AbstractTest.java
better to ignore test ATM as I'm not sure why it failed on non super privilege system.
Just added a bit of debug..
BTW test will not work on Windauze...
> Jetty 9.4.x 2014 unixsocket client ignore test

- jetty-bom/pom.xml
> 9.4.x branch remove pom dependency from bom and add type for non jar entries #2093

- jetty-bom/pom.xml
> 9.3.x branch remove non valid pom dependency from bom and add distrib with type #2093

- jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/client/HttpClientTransportOverUnixSockets.java
- jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/JnrTest.java
- jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketTest.java
> #2014 fix license header

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
- jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java
> Fixes #2117 - Allow to configure HttpClient default request Content-Type

- pom.xml
> Issue #2128 Revert surefire version

- jetty-util/src/main/java/org/eclipse/jetty/util/MultiException.java
- jetty-util/src/test/java/org/eclipse/jetty/util/MultiExceptionTest.java
Simplified MultiException to better use suppressed exceptions. #2075 
> Issue #2075 cleanup MultiException to better use suppressed

- jetty-util/src/main/java/org/eclipse/jetty/util/PathWatcher.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
- pom.xml
Enable errorprone compiler. ATM only warnings
> [WIP] Feature errorprone compiler

- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientLastAccessTimeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientModifyMaxInactiveIntervalTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientNonClusteredSessionScavengingTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientOrphanedSessionTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionExpiryTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionInvalidateCreateScavengeTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionMigrationTest.java
- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/client/ClientSessionScavengingTest.java
> use different instance name to avoid collision

- jetty-hazelcast/pom.xml
> upgrade to last hazelcast version 3.9.3

- jetty-home/pom.xml
- jetty-home/src/main/assembly/jetty-source-assembly.xml
replace PR #2158 for issue #2152 
this add nested sources as well.
> #2152 replace pr #2158

- Jenkinsfile
- jetty-maven-plugin/pom.xml
use -T2 for test stage and move junit,jacoco anf warning to a post block
> use a separated local maven repo per build and run maven in multi thread surefire configuration improvment

- jetty-osgi/test-jetty-osgi/pom.xml
> fix duplicate dependency

- jetty-osgi/test-jetty-osgi/pom.xml
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
> fix build with empty repo. add pax property with local maven repo used

- jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
> Issue #2255 - Notify SSL handshake failures on write failures.

- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/annotations/AnnotationConfiguration.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/annotations/AnnotationParser.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/BundleWebAppProvider.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/JettyBootstrapActivator.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/OSGiWebInfConfiguration.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/ServiceContextProvider.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/ServiceWebAppProvider.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/DefaultJettyAtJettyHomeHelper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/JettyServerServiceTracker.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/ServerInstanceWrapper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/webapp/LibExtClassLoaderHelper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/webapp/OSGiWebappClassLoader.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/BundleFileLocatorHelper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/EventSender.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/OSGiClassLoader.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/Util.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/internal/DefaultBundleClassLoaderHelper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/internal/DefaultFileLocatorHelper.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/utils/internal/PackageAdminServiceTracker.java
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootContextAsService.java
Made a stab at cleaning up imports, using <> etc etc.
> Jetty 9.4.x 2262 sanitize osgi code

- Jenkinsfile
https://issues.jenkins-ci.org/browse/JENKINS-46785
> simplify Jenkinsfile using new syntax

- jetty-io/src/main/java/org/eclipse/jetty/io/ConnectionStatistics.java
- jetty-server/src/main/java/org/eclipse/jetty/server/ConnectorStatistics.java
- jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
- jetty-util/src/main/java/org/eclipse/jetty/util/statistic/CounterStatistic.java
- jetty-util/src/main/java/org/eclipse/jetty/util/statistic/SampleStatistic.java
- jetty-util/src/test/java/org/eclipse/jetty/util/statistic/SampleStatisticTest.java
Cleaned up code, added Javadocs.
Renamed SampleStatistics.set(long) to record(long).
> Issue #2288 - Cleanup the statistics classes.

- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationConfiguration.java
- jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpClientTransportOverHTTP.java
- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpClientTransportOverFCGI.java
- jetty-fcgi/fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/proxy/FastCGIProxyServlet.java
- jetty-fcgi/fcgi-server/src/test/java/org/eclipse/jetty/fcgi/server/AbstractHttpClientServerTest.java
- jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
- jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
- jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ProxyServletLoadTest.java
- jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
- jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DataRateLimitedServlet.java
- jetty-util/src/main/java/org/eclipse/jetty/util/AtomicBiInteger.java
- jetty-util/src/main/java/org/eclipse/jetty/util/ProcessorUtils.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPoolBudget.java
- jetty-util/src/test/java/org/eclipse/jetty/util/ProcessorUtilsTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/QueueBenchmarkTest.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientLoadTest.java
> #2298 Override the processor number with an environment variable

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/MonitoredQueuedThreadPool.java
> Issue #2131 - Introduce a monitored thread pool.

- jetty-maven-plugin/pom.xml
- jetty-maven-plugin/src/it/jetty-run-distro-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/it/jetty-run-forked-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/it/jetty-start-mojo-it/jetty-simple-webapp/pom.xml
- pom.xml
> upgrade surefire version to 2.21.0

- jetty-bom/pom.xml
- pom.xml
> #2344 upgrade javadoc plugin to 3.0.0

- Jenkinsfile
- jetty-osgi/test-jetty-osgi/pom.xml
> fix using -DskipTests not skipping tests #2359

- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/CachingWebAppClassLoader.java
> Issue #2361 - CachingWebAppClassLoader is not using cache properly

- Jenkinsfile
- jetty-jspc-maven-plugin/pom.xml
- jetty-jspc-maven-plugin/src/it/settings.xml
- jetty-jspc-maven-plugin/src/it/simple-jsp-fail/invoker.properties
- jetty-jspc-maven-plugin/src/it/simple-jsp-fail/pom.xml
- jetty-jspc-maven-plugin/src/it/simple-jsp-fail/postbuild.groovy
- jetty-jspc-maven-plugin/src/it/simple-jsp-fail/src/main/jsp/foo.jsp
- jetty-jspc-maven-plugin/src/it/simple-jsp/invoker.properties
- jetty-jspc-maven-plugin/src/it/simple-jsp/pom.xml
- jetty-jspc-maven-plugin/src/it/simple-jsp/postbuild.groovy
- jetty-jspc-maven-plugin/src/it/simple-jsp/src/main/webapp/foo.jsp
- jetty-maven-plugin/pom.xml
- pom.xml
> [WIP] add it test for jspc plugin so we can test it with jdk10

- pom.xml
> use released jacoco 0.8.1

- jetty-jspc-maven-plugin/pom.xml
- jetty-maven-plugin/pom.xml
- pom.xml
> align maven version used #2373

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneHandler.java
- jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java
- jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
- jetty-util/src/main/java/org/eclipse/jetty/util/statistic/OnOffStatistic.java
> Jetty 9.4.x httpclient starvation gregw

- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/invoker.properties
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-base/pom.xml
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-base/src/main/java/org/eclipse/jetty/its/jetty_run_mojo_it/HelloServlet.java
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-base/src/main/java/org/eclipse/jetty/its/jetty_run_mojo_it/PingServlet.java
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-base/src/main/resources/META-INF/web-fragment.xml
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-webapp/src/main/webapp/WEB-INF/web.xml
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/jetty-simple-webapp/src/test/java/org/eclipse/jetty/its/jetty_run_war_mojo_it/TestGetContent.java
- jetty-maven-plugin/src/it/jetty-run-package-jar-mojo-it/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyDeployWar.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarExplodedMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStartMojo.java
> add list of supported packaging for run mojos #2372

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
> Issue #987 - remove checkGzExists from GzipHandler entirely

- jetty-jspc-maven-plugin/pom.xml
- jetty-jspc-maven-plugin/src/main/java/org/eclipse/jetty/jspc/plugin/JspcMojo.java
- jetty-maven-plugin/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyDeployWar.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyEffectiveWebXml.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunDistro.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunForkedMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarExplodedMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStartMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyWebAppContext.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/MavenQuickStartConfiguration.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/Overlay.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/OverlayConfig.java
> use maven annotations for jetty plugins #2404

- jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
- jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
> Issue #2387 - fixing URIUtil.equalsIgnoreEncoding() with jar:file:// uris

- jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSON.java
- jetty-util-ajax/src/test/java/org/eclipse/jetty/util/ajax/JSONTest.java
> Issue #2391 - JSON string encoding fix

- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/AbstractWebAppProvider.java
Checks before adding configuration classes based on availability of feature bundle in osgi to ensure no duplication.
> Issue #2409 Ensure no duplicate config classes in osgi

- Jenkinsfile
- jetty-osgi/test-jetty-osgi/pom.xml
- tests/test-sessions/test-infinispan-sessions/pom.xml
some tests need are disable in new maven profiles.
So we test with jdk10 for every changes (except the know not working yet with jdk10)
> add jdk10 in jenkinsfile and jdk10 maven profiles

- Jenkinsfile
> [WIP] add jdk11 in the jdk list

- pom.xml
> upgrade maven plugins

- jetty-documentation/src/main/asciidoc/reference/contributing/release-testing.adoc
- jetty-osgi/pom.xml
- jetty-osgi/test-jetty-osgi/pom.xml
- jetty-util/pom.xml
- jetty-util/src/main/config/modules/jul-slf4j.mod
- jetty-util/src/main/config/modules/log4j2-api.mod
- jetty-util/src/main/config/modules/logback-impl.mod
- jetty-util/src/main/config/modules/slf4j-api.mod
- pom.xml
> update logging versions #2461

- Jenkinsfile
- pom.xml
> test new local repository for CI and use PMD cache

- tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/HazelcastTestHelper.java
> no need to create different map per test as we clear it

- jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
- jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
- jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializer.java
- jetty-start/src/main/resources/org/eclipse/jetty/start/usage.txt
- jetty-start/src/test/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializerTest.java
> allow --add-to-start to specify maven repository location #2403

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/EatWhatYouKillTest.java
Added detection code for the concurrent produce case that must not happen.
> Issue #2468 - EWYK concurrent produce

- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
> Issue #2376 - relax ContextHandler requirements

- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarExplodedMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunWarMojo.java
This is a proof of concept of new language for the project skip logic in the `jetty-maven-plugin`.
@olamy we'll need some plugin IT tests for this setup.
> Issue #2496 - Improve plugin execution skip language

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
@gregw These are the only chanages that we did not both make I have fixed the logic so that a single host@connectorname entry allows the new behavior with an OR on each of the entries
Signed-off-by: Steve Bolton <steve@boltn.com>
> Issue #1785 Fix Javadoc and vhost warn logic

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
- jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
- jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartParser.java
- jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormInputStreamTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartParserTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/jmh/MultiPartBenchmark.java
Some code cleanup for the MultiPart changes.
Lazily create MultiException in MultiPartFormInputStream.deleteParts()
#1027 
> MultiPart Cleanup

- pom.xml
> [WIP] [DO NOT MERGE] remove link to self javadoc

- jetty-server/src/main/config/etc/jetty.xml
- jetty-server/src/main/config/modules/server.mod
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
- jetty-util/src/main/java/org/eclipse/jetty/util/SharedBlockingCallback.java
- jetty-util/src/test/java/org/eclipse/jetty/util/SharedBlockingCallbackTest.java
#2525 Clean up SharedBlockingCallback
> Issue #2525 Clean up SharedBlockingCallback

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpTokens.java
- jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartParser.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartParserTest.java
- jetty-http/src/test/resources/jetty-logging.properties
- jetty-http/src/test/resources/multipart/browser-capture-strange-quoting-apache-httpcomp.raw
Issue #2532 Better handling of tokens in parser
> Issue #2532 Better handling of tokens in parser

- .gitignore
- pom.xml
> [WIP] upgrade javadoc and plugin tools maven plugins

- jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
> Issue #2572 - Whitespace parsing test

- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/ByteAccumulator.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/CompressExtension.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/extensions/compress/ByteAccumulatorTest.java
> Issue #2603 - Improving ByteAccumulator testing and errors

- jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
- jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
> Issue #2556 - bad "file:" scheme present in Xml usage of "jetty.base" and "jetty.home" properties

- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/ServerInstanceWrapper.java
- jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
> Issue #2575 - OSGi Bundle.getEntry() does not escape URLs properly

- Jenkinsfile
- jetty-unixsocket/src/test/java/org/eclipse/jetty/unixsocket/UnixSocketTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
- pom.xml
> [WIP] Issue #2597 - Improving UnixSocketTest behavior.

- jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/AbstractLoginModule.java
Added null check when adding credentials to Set returned from getPrivateCredentials().  Fixes #2648
> Issue #2648 Added null check when adding credentials to Set

- jetty-start/src/test/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializerTest.java
> Issue #2650 delete file if exist to prevent build failure for non clean build 

- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
Closes #2398 
Improved comment describing charset behaviour for MultiPart
> Issue #2398 - MultiPart Charset Encoding 

- jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java
- jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
- jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
- jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
- jetty-util/src/main/java/org/eclipse/jetty/util/MultiException.java
- jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java
> Fixes #2663 - Guard Throwable.addSuppressed() calls.

- Jenkinsfile
> increase default build memory

- jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/DelayedStartClientOnServerTest.java
- jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/DefaultHttpClientProvider.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
- jetty-websocket/websocket-client/src/test/java/org/eclipse/jetty/websocket/client/ClientCloseTest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/scopes/SimpleContainerScope.java
- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/NativeWebSocketServletContainerInitializer.java
- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
> Issue #2655 - Removing closed WebSocket Session's from WebSocketClient

- jetty-home/src/main/resources/modules/conscrypt.mod
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
- pom.xml
Fixes https://github.com/google/conscrypt/issues/491
> fix #2342 Upgrade Conscrypt to 1.1.4

- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
- jetty-deploy/src/test/resources/jetty.xml
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerHTTPTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
- jetty-maven-plugin/src/it/jetty-cdi-run-forked/src/main/jetty/jetty.xml
- jetty-maven-plugin/src/it/jetty-deploy-war-mojo-it/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-forked-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-war-exploded-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-war-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-start-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/run-mojo-gwt-it/beer-server/src/config/jetty.xml
- jetty-osgi/jetty-osgi-boot/jettyhome/etc/jetty.xml
- jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty.xml
- jetty-server/src/main/config/etc/jetty.xml
- jetty-server/src/main/config/modules/server.mod
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
- tests/test-integration/src/test/resources/DefaultHandler.xml
- tests/test-integration/src/test/resources/RFC2616Base.xml
Signed-off-by: lachan-roberts <lachlan@webtide.com>
closes #2709
> Changing default Http headerCacheSize from 512 to 4096

- jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java
- jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2.java
- jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2Test.java
- jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/MaxConcurrentStreamsTest.java
#2672 
Now waiting for the server preface to arrive to the client before making
the connection available to the ConnectionPool.
> Fixes #2672 - Max local stream count exceeded for Http2 Client

- jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2Client.java
- jetty-http2/http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/frames/SettingsFrame.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/Parser.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/SettingsBodyParser.java
- jetty-http2/http2-common/src/test/java/org/eclipse/jetty/http2/frames/SettingsGenerateParseTest.java
- jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java
> Fixes #2722 - Improve configurability for SETTINGS frames.

- jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
- jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientAuthenticationTest.java
> Issue #2737 - Allow "=" characters in the AuthenticationProtocolHandler PARAM_PATTERN

- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
- jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
> Issue #1688 Encoded form content

- jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
> Issue #2755 - Managed Selector 100% CPU Spin

- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
#2757. Clarified the NetworkBuffer API semantic so that the code is now simpler.
> Issue #2757 - Possible double release of HTTP/2 ByteBuffers.

- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/ConfiguratorTest.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EchoCaptureHandler.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EndpointEchoClient.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EndpointEchoTest.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/MessageQueue.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/samples/EchoStringEndpoint.java
Updating unit tests to verify behavior in Issue #2768
> Issue #2768 - JSR356 Session.getUserProperties() is null during @OnOpen

- jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
- jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientAuthenticationTest.java
Splitting elements into list using QuotedCSV and processing with state machine instead of using regex to split into multiple challenges.
closes #2739
> Issue #2739 - AuthenticationProtocolHandler Multiple Challenge Pattern

- jetty-http2/http2-server/pom.xml
- pom.xml
> Issue #2778 upgrade h2spec-maven-plugin to 0.4

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneHandler.java
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
> Unwrap ServletException 9.3 #2787  

- jetty-osgi/test-jetty-osgi/pom.xml
- jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootCore.java
> fix osgi test with missing dependencies

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/DefaultHttpClientProvider.java
> Issue #2817 - Client SSL Defaults

- jetty-http-spi/pom.xml
- jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java
- jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestEndpointMultiplePublishProblem.java
- jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestSPIServer.java
> Issue #2718 - prevent NPE and IAE when changing Executor

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPoolBudget.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/AbstractThreadPoolTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/ExecutorThreadPoolTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java
> Issue #2798 thread budget warning default to available cores

- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
> Issue #2807 - Updating Default TLS Cipher Suite Exclusions

- jetty-client/src/main/java/org/eclipse/jetty/client/PoolingHttpDestination.java
- jetty-client/src/test/java/org/eclipse/jetty/client/http/HttpDestinationOverHTTPTest.java
Signed-off-by: Ivanov Anton <an.ivanov@corp.mail.ru>
> Issue #2860 Fix leakage of HttpDestinations in HttpClient

- jetty-distribution/pom.xml
- pom.xml
- tests/test-quickstart/pom.xml
I had to move a lot of the phases around for the generation of this, I think these are more proper configuration wise.
> Issue #2878 fix post release javadoc generation

- jetty-documentation/src/main/asciidoc/administration/startup/startup-unix-service.adoc
- jetty-documentation/src/main/asciidoc/reference/contributing/source-build.adoc
> java 8 required

- jetty-maven-plugin/src/it/jetty-cdi-run-forked/pom.xml
- jetty-maven-plugin/src/it/jetty-deploy-war-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-run-distro-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-run-forked-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-run-war-exploded-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-run-war-mojo-it/pom.xml
- jetty-maven-plugin/src/it/jetty-start-mojo-it/pom.xml
- jetty-maven-plugin/src/it/run-mojo-gwt-it/pom.xml
> align maven plugin versions

- jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
- jetty-jaas/src/test/java/org/eclipse/jetty/jaas/JAASLdapLoginServiceTest.java
> replace static dn by subtee based ldap lookup for an entry inside _userBaseDn

- jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestEndpointMultiplePublishProblem.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/AbstractThreadPoolTest.java
> get rid of remaining legacy junit

- jetty-maven-plugin/src/it/it-parent-pom/pom.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/api/pom.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/api/src/main/java/test/Api.java
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/invoker.properties
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/pom.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/postbuild.groovy
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/web/pom.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/web/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/web/src/main/java/test/ClassLoadingTestingServletContextListener.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
> Issue #2906 excluded reactor projects with provided scope

- jetty-distribution/pom.xml
> get rid of maven warning due to duplicate plugin declaration

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/test/BlockheadClientRequest.java
- jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/RedirectWebSocketClientTest.java
> Issues #2875 and #2901 WebSocketClient Redirected Upgrade

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
Issue #2912
I decided against fake chunked header to "ensure" HTTP/1.1 compliance, as that would just make us not HTTP/2 compliant.
> Issue #2912 Remove Content-Length from inflated requests

- jetty-osgi/test-jetty-osgi/pom.xml
- pom.xml
> fix osgi tests not running as paxexam is not junit5 ready

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneServletContext.java
- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterMapping.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ListenerHolder.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
- jetty-util/src/main/java/org/eclipse/jetty/util/component/DumpableCollection.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java
Cleanup after #2903
* Improved dump output of ServletHandler and ContextHandler
* Fixed duplicate listeners
* Removed unused fields
> Cleanup after #2903

- jetty-util/src/main/java/org/eclipse/jetty/util/MultiPartInputStreamParser.java
> Issue #2892 - NPE in MultiPartInputStreamParser#getPart

- pom.xml
> upgrade surefire plugin 2.22.1

- jetty-maven-plugin/src/it/it-parent-pom/pom.xml
> upgrade jackson-databind in maven it to 2.9.7

- jetty-maven-plugin/src/it/jetty-deploy-war-mojo-it/pom.xml
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/Configurations.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/ConfigurationsTest.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/MetaInfConfigurationTest.java
Issue #2985.  The problem only became apparent in the jetty-deploy-war-mojo-it test. When I fixed the problem I also created an explicit test for it.
> Issue #2985 Configuration replacement algorithm

- jetty-client/src/test/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTPTest.java
- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java
- jetty-fcgi/fcgi-client/src/test/java/org/eclipse/jetty/fcgi/parser/ClientParserTest.java
> Issue #3009 - Defaulting to non-LEGACY compliance modes

- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
- jetty-maven-plugin/src/it/jetty-run-distro-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunDistro.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunForkedMojo.java
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
> add javaPath to JettyRunDistro mojo to force a java executable to use (backport from 10.0.x branch)

- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
Issue #3030 Enforce Content-Encoding check only on parameter extraction.
> Issue #3030 Enforce Content-Encoding check only on parameter extraction.

- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl-distribution.adoc
- jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
- jetty-server/src/main/config/etc/jetty-ssl-context.xml
- jetty-server/src/main/config/modules/https.mod
- jetty-server/src/main/config/modules/ssl.mod
- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
Issue #3049 Warn on common SslContext vulnerable configurations
> Issue #3049 Warn on common SslContext vulnerable configurations

- jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DefaultServletTest.java
Issue #3023 redirect to / when pathInfoOnly
> Issue #3023 redirect to / when pathInfoOnly

- jetty-documentation/src/main/asciidoc/reference/troubleshooting/troubleshooting-locked-files.adoc
Update the troubleshooting do on file locking to show how to directly configure the plugin, and remove old ways to configure it.
> Issue #2925 Update troubleshooting doc for files locking on windows

- jetty-server/src/main/config/etc/jetty.xml
- jetty-server/src/main/config/modules/server.mod
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
Issue #3041 separate CookieCompliance for parsing and generation.
Also improved dump of HttpConfiguration
> Issue #3041 separate CookieCompliance for parsing and generation

- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
- tests/test-webapps/test-servlet-spec/test-container-initializer/src/main/java/com/acme/initializer/FooInitializer.java
- tests/test-webapps/test-servlet-spec/test-spec-webapp/src/main/java/com/acme/test/AnnotatedListener.java
- tests/test-webapps/test-servlet-spec/test-spec-webapp/src/main/java/com/acme/test/TestListener.java
Issue #3097 
The call to super.addEventListener() in the ServletContextHandler.Context.addListener(Listener) method was adding a programmatically added listener twice.
> Issue #3097 Duplicated programmatic listeners.

- pom.xml
> Adding profile to ensure release uses JDK11 (or newer)

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
- jetty-client/src/main/java/org/eclipse/jetty/client/ProtocolHandlers.java
- jetty-client/src/main/java/org/eclipse/jetty/client/ResponseNotifier.java
- jetty-client/src/test/java/org/eclipse/jetty/client/AbstractHttpClientServerTest.java
- jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
- jetty-client/src/test/java/org/eclipse/jetty/client/HttpConnectionLifecycleTest.java
- jetty-client/src/test/java/org/eclipse/jetty/client/ValidatingConnectionPoolTest.java
- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslSelectionDump.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientLoadTest.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportScenario.java
#3103 
Add or update beans in constructor or setter rather than in doStart
> Issue #3103 - HttpClient buffer leak found by dump improvements

- jetty-bom/pom.xml
This PR removes duplicate declarations from the `bom` artifact.  Instead, we inherit it from `jetty-project` and use the `maven-flatten-plugin` to sanitize the bom before publishing.
Here is a diff of the changes to the final bom:
`[steven@nevets:~/code/jetty.project/jetty-bom](flatten-bom-9.4|…)% python ~/xmldiffs.py /Users/steven/.m2/repository/org/eclipse/jetty/jetty-bom/9.4.14-SNAPSHOT/jetty-bom-9.4.14-SNAPSHOT.pom flattened-pom.xml | sed 's%{http://maven.apache.org/POM/4.0.0}%%g'`
```diff
--- /Users/steven/.m2/repository/org/eclipse/jetty/jetty-bom/9.4.14-SNAPSHOT/jetty-bom-9.4.14-SNAPSHOT.pom
+++ flattened-pom.xml
@@ -1,73 +1,7 @@
-<project {http://www.w3.org/2001/XMLSchema-instance}schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"> …
```
> bom: inherit project; use flatten plugin to sanitize bom

- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java
- jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
> Jetty 9.4.x 3117 retainable byte buffer

- jetty-documentation/src/main/asciidoc/administration/extras/qos-filter.adoc
Signed-off-by: Pawel Nawrocki <pnaw94@hotmail.com>
> Fixed invalid QoS Filter parameter names

- jetty-documentation/src/main/asciidoc/development/frameworks/osgi.adoc
- jetty-osgi/test-jetty-osgi/pom.xml
Signed-off-by: Raymond Auge <raymond.auge@liferay.com>
> fixes #3141 Upgrade jetty osgi tests to use spifly 1.2

- jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java
- jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServerProvider.java
- jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestEndpointMultiplePublishProblem.java
> Issue #2718 take care of starting new created context

- jetty-gcloud/jetty-gcloud-session-manager/pom.xml
- jetty-home/pom.xml
- jetty-infinispan/pom.xml
- jetty-maven-plugin/pom.xml
- jetty-osgi/test-jetty-osgi/pom.xml
- pom.xml
> activate Maven enforcer Upper bound dependencies check

- jetty-maven-plugin/src/it/javax-annotation-api/pom.xml
- pom.xml
> interpolate version from main pom for maven plugin it test (backport from 10.0.x)

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/WebSocketJsrServer.java
- jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/deploy/WebSocketServerContainerInitializer.java
- jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/ConfiguratorTest.java
> Fixes #3139 - NPE in WebSocketContainerInitializer

- jetty-maven-plugin/src/it/it-parent-pom/pom.xml
> Upgrade jackson-databind to version 2.9.8

- jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
- jetty-websocket/javax-websocket-tests/src/main/java/org/eclipse/jetty/websocket/javax/tests/NetworkFuzzer.java
- jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/client/DecoderReaderManySmallTest.java
- jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/server/IdleTimeoutTest.java
- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/ExtensionStack.java
> Issue #3246 - javax-websocket-tests exception stacktraces

- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpClientTransportOverFCGI.java
- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpConnectionOverFCGI.java
- jetty-fcgi/fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/proxy/FastCGIProxyServlet.java
- jetty-fcgi/fcgi-server/src/test/java/org/eclipse/jetty/fcgi/server/AbstractHttpClientServerTest.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpChannelAssociationTest.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientLoadTest.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportScenario.java
> Fixes #2095 - Remove FastCGI multiplexing.

- jetty-osgi/jetty-osgi-boot-jsp/build.properties
- jetty-osgi/jetty-osgi-boot-warurl/build.properties
- jetty-osgi/jetty-osgi-boot/build.properties
- jetty-osgi/jetty-osgi-httpservice/build.properties
Issue #3280 
Old unused files can be removed.
> Issue #3280 Remove unused build.properties from osgi

- jetty-maven-plugin/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/invoker.properties
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/postbuild.groovy
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/src/main/java/com/acme/Counter.java
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/src/main/webapp/WEB-INF/web.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/src/main/webapp/jsp/bean1.jsp
- jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/it/TestGetContent.java
- pom.xml
> Issue #3254 add jsp test need to remove cdi-api and exclude it from upperBound rule

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/WebSocketJsrServer.java
- jetty-websocket/javax-websocket-server/src/main/java/org/eclipse/jetty/websocket/javax/server/JavaxWebSocketServerContainer.java
same changes from #3155 to fix #3139 in jetty10
> Issue #3139 - NPE in WebSocketContainerInitializer for jetty10

- jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
Using system property "org.eclipse.jetty.io.forceSelectNow"
to force a selectNow() call; if absent, forcing selectNow()
only in the Windows OS.
> Fixes #3305 - Avoid additional selectNow().

- jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
Signed-off-by: alexey.barsov <foster_licey_reg@mail.ru>
> Issue #3302 Supporting host:ip in X-Forwarded-For

- jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionCache.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
#3308 
I should have removed these methods when I merged #3284 through to jetty-10.
> Issue #3308 Remove deprecated session methods

- Jenkinsfile
- jetty-jmh/pom.xml
- jetty-jmh/src/main/java/org/eclipse/jetty/http/jmh/MultiPartBenchmark.java
- pom.xml
- tests/test-distribution/src/main/java/org/eclipse/jetty/tests/distribution/DistributionTester.java
The idea behind this change is to build/deploy the aggregated javadoc as part of the release
> Issue #2878 - Fixing aggregated javadoc jar

- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/ClientUpgradeRequest.java
- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/server/internal/RFC6455Handshaker.java
Signed-off-by: Joakim Erdfelt <joakim@erdfelt.com>
> Issue #3380 - Adding configured Connection.Listeners to WebSocket Connections

- jetty-websocket/javax-websocket-server/pom.xml
> Issue #3165 use add-exports instead of add-opens in javax WS-Server pom

- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/SelectiveJarResource.java
- jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/AbstractWebAppProvider.java
- jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/PreconfigureQuickStartWar.java
- jetty-runner/src/main/java/org/eclipse/jetty/runner/Runner.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResourceCacheTest.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/EmptyResource.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarFileResource.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarResource.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceCollection.java
- jetty-util/src/main/java/org/eclipse/jetty/util/resource/URLResource.java
- jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceCollectionTest.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/OrderingTest.java
- jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
- tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/QuickStartTest.java
- tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/Quickstart.java
> Issue #1676 - Removing Deprecated Resource.getURL()

- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/OnMessageBinaryCallable.java
- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/annotations/OnMessageTextCallable.java
- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/messages/BinaryWholeMessage.java
- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/messages/TextWholeMessage.java
- jetty-websocket/javax-websocket-server-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/server/EchoTest.java
> Issue #3389 javax.websocket willDecode

- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/PerMessageDeflateExtension.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/extensions/FragmentExtensionTest.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/extensions/compress/PerMessageDeflateExtensionTest.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/test/OutgoingFramesCapture.java
> Issue #3159 - Ensuring we follow permessage-deflate RSV1 rules in RFC7692

- jetty-security/src/main/java/org/eclipse/jetty/security/authentication/LoginAuthenticator.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
- tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/CreationTest.java
- tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SessionRenewTest.java
Issue #3421 Duplicate session set-cookie
Added Response.replaceCookie
use replaceCookie in sessions
unit tests
> Issue #3421 Duplicate session set-cookie

- jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java
- jetty-websocket/javax-websocket-common/src/main/java/org/eclipse/jetty/websocket/javax/common/SessionTracker.java
- jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/server/SessionTrackingTest.java
- jetty-websocket/jetty-websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
- jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
- jetty-websocket/jetty-websocket-common/src/test/java/org/eclipse/jetty/websocket/common/EventQueue.java
- jetty-websocket/jetty-websocket-common/src/test/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerTest.java
- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/BadNetworkTest.java
- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientSessionsTest.java
- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/ServerCloseTest.java
- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketChannelState.java
> Issue #3406 - restore jetty websocket tests

- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/App.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/AppProvider.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentManager.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/DebugListenerBinding.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/GlobalWebappConfigBinding.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/graph/Graph.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/jmx/DeploymentManagerMBean.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ScanningAppProvider.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java
- jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/jmx/WebAppProviderMBean.java
- jetty-deploy/src/test/java/org/eclipse/jetty/deploy/JmxServiceConnection.java
+ Fixing up some bad JMX attributes as well.
> Issue #3429 - Adding WebAppProvider.scan() method to JMX

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketConnectionStatsTest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/Parser.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/FrameFlusher.java
> Issue #3106 - backport WebSocket connection stats from jetty-10

- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java
+ Moving Resource.newResource() to later point
> Issue #3489 - Allowing JAR directory references on Windows

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java
While debugging `ClientCloseTest.testStopLifeCycle()` for #3494, I noticed that the when the `QueuedThreadPool` was being stopped, jobs could be taken out of the `QueuedThreadPool` job queue and never run
these changes make it so if a job is taken from the job queue in `QueuedThreadPool`, then it is always run
if there are still jobs in the queue after the thread pool has been stopped, they are closed if they implement `Closeable` otherwise a warning is logged
>  QueuedThreadPool bug - jobs disappearing on lifecycle stop #3494

- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
> Issue #3530 - Warning on attempt to use WebSocket Bootstrap on HTTP/2

- jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java
- jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
+ If optional Security Provider is configured, then use it consistently
for all security objects that take a Provider argument.
> Issue #3540 - Use configured Security Provider consistently

- jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
> Issue #3545 - NPE in HttpOutput with print("")

- jetty-util/src/main/java/org/eclipse/jetty/util/component/DumpableCollection.java
- jetty-util/src/test/java/org/eclipse/jetty/util/component/DumpableCollectionTest.java
#3587 
Fix NPE in DumpableCollection and add test case.
> Issue #3597 NPE in DumpableCollection

- jetty-bom/pom.xml
Added new infinispan dependencies. I did not add a dependency for infinispan-common because I assume it is included as a transitive dependency of the others?
> Issue #3573 Update bom for infinispan.

- jetty-io/src/main/java/org/eclipse/jetty/io/IdleTimeout.java
#3534.
Removed usages of System.currentTimeMillis() and cleaned up the code.
> Fixes #3534 - Don't use System.currentTimeMillis() in IdleTimeout.

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
> fix flaky test ClientCloseTest.testWriteException

- jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
Signed-off-by: Gary Gregory <garydgregory@gmail.com>
> Allow subclasses to map exceptions to status codes.

- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/ClientContainer.java
- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/JsrSessionListener.java
- jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/JsrSessionTracker.java
- jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/ServerContainer.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/SessionTracker.java
- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
> Issue #3616 - Backport of WebSocket SessionTracker from Jetty 10

- tests/test-distribution/src/main/java/org/eclipse/jetty/tests/distribution/DistributionTester.java
> force using local repo to download module dependencies

- scripts/release-jetty.sh
> deploy aggregated javadoc as well during release

- jetty-maven-plugin/src/it/it-parent-pom/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/jetty-simple-base/src/test/java/org/eclipse/jetty/its/jetty_run_mojo_it_test/HelloTestServlet.java
- jetty-maven-plugin/src/it/jetty-run-mojo-it/jetty-simple-webapp/pom.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/pom.xml
- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
- jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/it/TestGetContent.java
> Issue #3583 maven plugin do not use testOutputDirectory directory for test dependencies within reactor

- pom.xml
> upgrade maven plugins and configure clean plugin version

- apache-jsp/src/main/java/org/eclipse/jetty/jsp/JettyJspServlet.java
- examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyHandlers.java
- jetty-cdi/cdi-websocket/src/main/java/org/eclipse/jetty/cdi/websocket/WebSocketCdiListener.java
- jetty-fcgi/fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/HttpChannelOverFCGI.java
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
- jetty-http/src/main/java/org/eclipse/jetty/http/MimeTypes.java
- jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
- jetty-http/src/main/java/org/eclipse/jetty/http/PathMap.java
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/CookieDump.java
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/SessionDump.java
Small minor performance improvements
Signed-off-by: Michael Hausegger <hausegger.michael@googlemail.com>
> Small minor performance improvements

- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/util/ReflectUtilsTest.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/util/TextUtilTest.java
Added Unit Tests to increase code coverage.
> Add unit tests two

- jetty-cdi/cdi-core/src/test/java/org/eclipse/jetty/cdi/core/NamedLiteralTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/DateParserTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpSchemeTest.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/UpgradeResponseAdapterTest.java
Added Unit Tests to increase code coverage.
> Add unit tests three

- jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
- jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushCacheFilter.java
- jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
- jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSON.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/ChatServlet.java
Added small performance improvements.
Signed-off-by: Michael Hausegger <hausegger.michael@googlemail.com>
> Added small performance improvements

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
- jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
- jetty-security/src/test/java/org/eclipse/jetty/security/ConstraintTest.java
- jetty-server/src/main/java/org/eclipse/jetty/server/CookieCutter.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
- jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutterTest.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
> Issue #3655 simplifications of Cookie handling

- jetty-util/src/test/java/org/eclipse/jetty/util/ArrayUtilTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/IntrospectionUtilTest.java
- jetty-util/src/test/java/org/eclipse/jetty/util/LoaderTest.java
Added additional Unit Tests to increase code coverage.
Signed-off-by: Michael Hausegger <hausegger.michael@googlemail.com>
> Added additional Unit Tests to increase code coverage

- pom.xml
> Issue #3690 Upgrade to asm 7.1

- jetty-websocket/javax-websocket-client/src/main/java/org/eclipse/jetty/websocket/javax/client/JavaxWebSocketClientContainer.java
- jetty-websocket/javax-websocket-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/client/misbehaving/MisbehavingClassTest.java
> Issue #3696 - unwrap ExecutionException in javax WS connectToServer

- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/decoders/FloatDecoderTest.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/decoders/LongDecoderTest.java
- jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/decoders/ShortDecoderTest.java
- jetty-websocket/websocket-common/src/test/java/org/eclipse/jetty/websocket/common/util/ReflectUtilsTest.java
Added Unit Tests to increase code coverage.
> Add unit tests five

- jetty-util/src/main/config/modules/log4j2-api.mod
- jetty-util/src/main/config/modules/log4j2-impl.mod
- jetty-util/src/main/config/modules/log4j2-impl/resources/log4j2.xml
- pom.xml
- tests/test-distribution/src/main/java/org/eclipse/jetty/tests/distribution/DistributionTester.java
- tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
add disruptor jar if users wants to use async logging
> upgrade log4j2 version and fix log4j2.xml provided sample

- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/MultiPartConfigAnnotationHandler.java
- jetty-annotations/src/main/java/org/eclipse/jetty/annotations/RunAsAnnotationHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java
Cleanups when checking thread safety of lazy servlet/filter introspection #3749 #3755
+ Handle multiple holders for annotated servlets
+ Replaced duplicate code with common methods
> Servlet Context/Handler/Holder  cleanups

- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java
> Issue #3736 - Give better exception when using bad classloader impl

- jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
- jetty-io/src/test/java/org/eclipse/jetty/io/WriteFlusherTest.java
> Issue #3746 - fix WriteFlusher ClassCastException if Callback throws

- Jenkinsfile
> store autobahn results as they are not stored automatically by junitPublisher

- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/scopes/SimpleContainerScope.java
> Issue #3648 - SSL based on WebSocket behavior (CLIENT vs SERVER)

- examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java
- jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java
- jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java
RewriteHandler dumps it's rules
> Dumpable RewriteHandler

- build-resources/jetty-codestyle-eclipse-ide.xml
I've made mods to this style to try and make it conform with what intellij produces. Still not quite there, but there may be some differences that we will have to live with.
@joakime can you test this out in your eclipse as well?
> Fix Eclipse java style for jetty

- build-resources/src/main/resources/jetty-checkstyle.xml
- build-resources/src/main/resources/jetty-suppressions.xml
- pom.xml
+ No MethodNameCheck
+ No TypeNameCheck
+ No LocalVariableNameCheck
> Adding CheckStyle suppression's for src/test/java

- jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
- jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
Issue #3805 Trim space on around XmlConfiguration fields
Improved field set type transformation
improved string trimming
improved comments
> Issue #3805 Trim space on around XmlConfiguration fields

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ListenerHolder.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
- tests/test-distribution/pom.xml
- tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DynamicListenerTests.java
- tests/test-distribution/src/test/resources/realm.ini
- tests/test-distribution/src/test/resources/realm.properties
- tests/test-distribution/src/test/resources/test-realm.xml
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/AddListServletRequestListener.java
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/TestListener.java
- tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/TestServlet.java
- tests/test-webapps/test-jetty-webapp/src/main/webapp/WEB-INF/web.xml
#3799 
Programmatic listeners that are added from ServletContextListeners were not being initialized and called correctly. Fixed and added extensive unit test.
> Issue #3799 Programmatic listeners from ServletContextListeners.

- jetty-util/src/main/java/org/eclipse/jetty/util/IncludeExcludeSet.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClasspathPattern.java
Issue #3700 better handling of null location
If location is null, the match may success if there are no location inclusions 
> Issue #3700 better handling of null location

- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java
- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketSessionState.java
- jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/proxy/WebSocketProxy.java
> Issue #3849 - only notify onError for local errors

- jetty-util/src/main/java/org/eclipse/jetty/util/compression/CompressionPool.java
> fix modifier order checkstyle 0!!

- jetty-gcloud/jetty-gcloud-session-manager/pom.xml
- pom.xml
- tests/test-sessions/test-gcloud-sessions/pom.xml
> avoid transitive dependency on a range version which can failed the build

- pom.xml
> make jetty-all build tested by ci build to avoid issue at release time

- jetty-server/src/main/java/org/eclipse/jetty/server/session/DatabaseAdaptor.java
Fixes https://github.com/eclipse/jetty.project/issues/3890
> Made loading of blobs from database more robust

- jetty-util/src/main/java/org/eclipse/jetty/util/Jetty.java
>  Issue #3918 use Jetty version from pom if not found

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/PartialListenerTest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyListenerEventDriver.java
> Issue #3876 - WebSocket Partial Listener testcases and fix

- jetty-home/pom.xml
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/HugeResourceTest.java
- pom.xml
This is to help CI and @olamy when disk space is low.
> Skip large file test if not enough disk space available.

- jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
- jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java
#3940.
Removed usage of StringUtil.
Restructured the class and cleaned up the code.
> Fixes #3940 - Double initialization of Log.

- tests/test-webapps/test-servlet-spec/test-spec-webapp/pom.xml
- tests/test-webapps/test-servlet-spec/test-spec-webapp/src/main/java/com/acme/test/MultiPartTest.java
> sanitize xml from multipart upload in MultiPartTest

- jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
- jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ServletRequestWrapperTest.java
In some case (some tck tests) the request can be ServletRequestWrapper
> Jetty 9.4.x fix some part of the code assuming cast to HttpServletRequest is possible

- pom.xml
> include test sources in checkstyle check

- jetty-jmh/src/main/java/org/eclipse/jetty/requestlog/jmh/RequestLogBenchmark.java
- jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
> Issue #3957 - fix bad usage of MethodHandles.lookup()

- tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java
- tests/test-webapps/test-cdi-common-webapp/src/main/webapp/index.html
- tests/test-webapps/test-owb-cdi-webapp/pom.xml
- tests/test-webapps/test-owb-cdi-webapp/src/main/webapp/WEB-INF/jetty-web-owb.xml
Fixed bad names in OWB webapp.
Don't have the owb jetty-web.xml on by default.
> Fixed decoration changes for #3804

- jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> Issue #3969 - adding testcase to verify Host & X-Forwarded behavior

- jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
- jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormInputStreamTest.java
see https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/Part.html#getHeaders-java.lang.String-
this fix related tck test
> Part.html#getHeaders(String) is not supposed to return null

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
test was fixed in 10.0.x for issue #3494 but fix was never added back to 9.4.x
see first commit for only the fix for the `testStopLifecycle()`
second commit is cleanup of the rest of `ClientCloseTest`
> fix flaky test ClientCloseTest.testStopLifecycle() in jetty 9.4.x

- jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
- jetty-server/src/test/java/org/eclipse/jetty/server/session/SessionHandlerTest.java
fix tck test.
https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpSession.html#getLastAccessedTime--
> session#getLastAccessedTime should throw IllegalStateException if session has been invalidated

- jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
- jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
- jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
- jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
+ Allows for preserving bad percent sequences "X%YZ"
> Issue #4033 - Add Lenient percent decode in URIUtil

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java
+ Preventing HttpField from having a null name.
> Issue #4057 - NPE in HttpFields.containsKey

- pom.xml
> Inherit local settings file to force usage of mirrors etc.. if any

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java
- jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/ConnectionState.java
> Issue #4031 - stop unopened WebSocketSessions gracefully

- jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
Support multiple proxy port values.
> Issue #4048 Multiple proxy ports

- jetty-documentation/src/main/asciidoc/quick-start/introduction/what-version.adoc
> Updating versions table

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPoolBudget.java
> ThreadPoolBudget.check() throws incorrect error messages #4070

- jetty-security/src/test/java/org/eclipse/jetty/security/SessionAuthenticationTest.java
Add test for SessionAuthentication serializability.
> Issue #4072 Add test for SessionAuthentication serialization

- jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
- tests/test-integration/src/test/java/org/eclipse/jetty/test/FailedSelectorTest.java
- tests/test-integration/src/test/resources/jetty-logging.properties
This is similar to PR #4002, except this one is for Jetty 9.4.x
> Issue #3989 - add new onSelectFailure method overridable

- jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/client/ClientUpgradeRequest.java
> Fixes #3705 - revert ClientUpgradeRequest error handling logic

- jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyWebAppContext.java
- jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java
- jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartGeneratorConfiguration.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/AbstractConfiguration.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/Configuration.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/Configurations.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/WebAppContextTest.java
- tests/test-integration/src/test/java/org/eclipse/jetty/test/DeploymentErrorTest.java
> Configuration cleanup

- jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
- jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java
This fixes a race where `ensureThreads()` could start more threads than necessary.
The loop in `ensureThreads()` wants to keep making new threads while `idle < 0`, but `idle` is only incremented by the thread that is created, this causes the race which can result in the creation of excess idle threads. See issue #4105.
Now the number of idle threads are incremented before starting the thread which eliminates the race. 
The new test `QueuedThreadPoolTest.testEnsureThreads()` reproduces the issue.
> Issue #4105 - atomically increment idle count when starting new thread in QTP

- jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/ForwardedSchemeHeaderRule.java
- jetty-security/src/main/java/org/eclipse/jetty/security/authentication/DigestAuthenticator.java
> Fixing #4144 - handle wrapped requests better

- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletWrapperTest.java
> Fixes #4141 - Servlet not async + async Filter + wrapped request

- jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java
This PR fixes the issue described in #4134 where the audience (`aud`) claim might be an array instead of a simple string.
> Issue #4134 - Validate audience (aud) claim as list or string, not just string

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
- jetty-http/src/main/java/org/eclipse/jetty/http/HttpHeader.java
- jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/HTTP2Test.java
- jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/TrailersTest.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Flusher.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/FrameGenerator.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/Generator.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/HeadersGenerator.java
- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/PushPromiseGenerator.java
- jetty-http2/http2-common/src/test/java/org/eclipse/jetty/http2/frames/FrameFloodTest.java
- jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackContext.java
- jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
- jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackEncoderTest.java
- jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackPerfTest.java
- jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackTest.java
- jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2Test.java
- jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
> Fixes #4115 - Drop HTTP/2 pseudo headers.

- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
#4179 
The HttpConnection.SendCallback nulls it's reference to buffers and callbacks after completion to assist with easy GC, since the connection callback is a long lived instance.
> Issue #4179 SendCallback GC

- jetty-documentation/src/main/asciidoc/configuring/security/serving-aliased-files.adoc
Signed-off-by: Julien Gouesse <gouessej@orange.fr>
> Fixes some spelling mistakes, see issue #4160

- jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/WindowRateControl.java
- jetty-http2/http2-server/src/main/config/etc/jetty-http2.xml
- jetty-http2/http2-server/src/main/config/etc/jetty-http2c.xml
- jetty-http2/http2-server/src/main/config/modules/http2.mod
- jetty-http2/http2-server/src/main/config/modules/http2c.mod
> Issue #4142 - module config for http2 maxSettingsKeys and RateControl

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java
- jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
- jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
Cleanup and simplify code for speculative #4188 fix
> Issue #4188 Spin in close of GzipHandler

- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClasspathPattern.java
- jetty-webapp/src/test/java/org/eclipse/jetty/webapp/ClasspathPatternTest.java
Rework logic of ClasspathPattern test logic that combines testing a name and location against name/package patterns and location patterns. A name matches if it is not excluded by either  pattern  and either included by at least one pattern or there are no includes. When the location is null and there are location exclusions, it is considered NOT to match because we can't check the exclusions. If there are no location exclusions, if there are location inclusions it must be included.
> Issue #4183 Handle null class location for ClasspathPattern.

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
>  Issue #4222 Jetty 10.0.x fix major minor version

- jetty-documentation/src/main/asciidoc/configuring/security/serving-aliased-files.adoc
Signed-off-by: Julien Gouesse <gouessej@orange.fr>
> Issue #4160, fixes some spelling mistakes

- jetty-server/pom.xml
- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
> Issue #4243  invalid json error response from ErrorHandler

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
#4264 revert the doError signature.
> Issue #4264 Revert doError signature

- README.md
This is a test of PR auto building.
> Updating http to https

- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpClientTransportOverHTTP.java
- jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
- jetty-deploy/src/test/resources/jetty.xml
- jetty-documentation/src/main/asciidoc/development/maven/jetty-maven-plugin.adoc
- jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerHTTPTest.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
- jetty-maven-plugin/src/it/javax-annotation-api/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-cdi-run-forked/src/main/jetty/jetty.xml
- jetty-maven-plugin/src/it/jetty-deploy-war-mojo-it/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-maven-plugin-provided-module-dep/web/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-forked-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-jsp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-mojo-multi-module-single-war-it/webapp-war/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-war-exploded-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-run-war-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/jetty-start-mojo-it/jetty-simple-webapp/src/config/jetty.xml
- jetty-maven-plugin/src/it/run-mojo-gwt-it/beer-server/src/config/jetty.xml
- jetty-osgi/jetty-osgi-boot/jettyhome/etc/jetty.xml
- jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty.xml
- jetty-server/src/main/config/etc/jetty.xml
- jetty-server/src/main/config/modules/server.mod
- jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
- tests/test-integration/src/test/resources/DefaultHandler.xml
- tests/test-integration/src/test/resources/RFC2616Base.xml
> Issue #2709 - reduce default headerCacheSize to 1024

- jetty-alpn/jetty-alpn-openjdk8-client/src/main/java/org/eclipse/jetty/alpn/openjdk8/client/OpenJDK8ClientALPNProcessor.java
- jetty-alpn/jetty-alpn-openjdk8-client/src/main/resources/META-INF/services/org.eclipse.jetty.io.ssl.ALPNProcessor$Client
> Fixes #4283 - Wrong package for OpenJDK8ClientALPNProcessor.

- jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
- tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientDemandTest.java
Fixed handling of demand in case of gzipped response content.
> Fixes #4277 - Reading streamed gzipped body never terminates.

- jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
- jetty-server/src/test/java/org/eclipse/jetty/server/DelayedServerTest.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ExtendedServerTest.java
- jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
- tests/test-integration/pom.xml
- tests/test-integration/src/test/java/org/eclipse/jetty/test/PersistentFileUploadDownloadTest.java
- tests/test-integration/src/test/resources/jetty-logging.properties
- tests/test-integration/src/test/resources/logback.xml
Issue #4161 Write LifeCycleViolation
Do not callback on write completion until after state has been changed and notifications made.
> Issue #4161 Write LifeCycleViolation

- jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientConnectTest.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java
> Fixes #4296 - WebSocketClient cannot connect with "%25" in query

- jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java
> Issue #4236 - move redirect code calculation to utility method

- jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/FilterHolder.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ListenerHolder.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
- jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java
- jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java
A minor cleanup of the ServletContext implementation classes for #2340
> Issue #2340 ServletContext cleanup

- jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
- jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
- jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
#4247
Allows sameSite cookie settings to be configured in SessionCookieConfig comments
> Issue #4247 SameSite Session Cookie

- jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/UpgradeResponse.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeResponse.java
- jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketUpgradeRequest.java
- jetty-websocket/websocket-client/src/test/java/org/eclipse/jetty/websocket/client/CookieTest.java
- jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
> Fixes #4248 - WebSocketClient UpgradeResponse.isSuccess never set true

- jetty-server/src/main/java/org/eclipse/jetty/server/ResponseWriter.java
- jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
This is for release Jetty 9.4.24
> Issue #4269 - Restoring PrintWriter contract on errors
